/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
myprofile: Korax254 (https://sketchfab.com/Tonifo254)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ufo-abduction-pigs-0963d712d6fc4e11a451ac8b4f235f29
title: UFO Abduction Pigs
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Abduction({ ...props }) {
    const group = useRef();
    const { nodes, materials } = useGLTF("/abduction.glb");
    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group
                        position={[0, -81.49, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={[1, 1, 0.35]}
                    >
                        <mesh
                            geometry={nodes.Grass_Grass_0.geometry}
                            material={materials.Grass}
                        />
                    </group>
                    <group
                        position={[0, 29.42, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                    >
                        <mesh
                            geometry={nodes.UFO_UFO_0.geometry}
                            material={materials.material}
                        />
                    </group>
                    <group
                        position={[-0.14, 10.53, 0.04]}
                        rotation={[-Math.PI / 2, 0, 0]}
                    >
                        <mesh
                            geometry={nodes.Light_Light_0.geometry}
                            material={materials.Light}
                        />
                    </group>
                    <group
                        position={[0, -60.09, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                    >
                        <mesh
                            geometry={nodes.Pig_Pig_0.geometry}
                            material={materials.material_3}
                        />
                    </group>
                </group>
            </group>
        </group>
    );
}

// useGLTF.preload("/abduction.glb");
