/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Armor.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Armor.geometry}
        material={materials["Armor Plates"]}
      />
      <mesh
        geometry={nodes.Armor_1.geometry}
        material={materials["Armor Mech"]}
      />
    </group>
  );
}

// useGLTF.preload('/Armor.glb')
