/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/AstraFull-transformed.glb");

  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[0, 2.67, 102.17]} rotation={[1.57, 0, 0]}>
            <group rotation={[0.23, 0, 0]}>
              <group
                position={[9.05, -1.84, -0.78]}
                rotation={[-0.19, 0, 3.12]}
              >
                <group position={[0, 43.55, 0]} rotation={[0.03, 0, 0]}>
                  <group
                    position={[0, 43.27, 0]}
                    rotation={[1.27, -0.02, 0.11]}
                  >
                    <group
                      position={[0, 13.4, 0]}
                      rotation={[0.28, 0.05, -0.04]}
                    />
                  </group>
                </group>
              </group>
              <group
                position={[-9.05, -1.84, -0.78]}
                rotation={[-0.19, 0, -3.12]}
              >
                <group position={[0, 43.55, 0]} rotation={[0.03, 0, 0]}>
                  <group
                    position={[0, 43.27, 0]}
                    rotation={[1.27, 0.02, -0.11]}
                  >
                    <group
                      position={[0, 13.4, 0]}
                      rotation={[0.28, -0.05, 0.04]}
                    />
                  </group>
                </group>
              </group>
            </group>
            <group position={[0, 7.12, 1.64]} rotation={[0.27, 0, 0]}>
              <group position={[0, 4.09, 0]} rotation={[-0.38, 0, 0]}>
                <group position={[0, 13.33, 0]} rotation={[-0.11, 0, 0]}>
                  <group position={[0, 26.71, 0]} rotation={[0.44, 0, 0]}>
                    <group position={[0, 3.75, 0]} rotation={[0.04, 0, 0]}>
                      <group position={[0, 3.56, 0]} rotation={[-0.26, 0, 0]}>
                        <group rotation={[1.57, Math.PI / 2, 0]}>
                          <group
                            position={[1.16, 2.38, 0]}
                            rotation={[0, 0, 1.57]}
                          >
                            <group
                              position={[3.01, 0.9, 0]}
                              rotation={[0, 0, 0.11]}
                            >
                              <group
                                position={[1.06, 0, 0]}
                                rotation={[0, 0, 0.18]}
                              />
                            </group>
                          </group>
                          <group
                            position={[2.63, 6.31, 0]}
                            rotation={[0, 0, 1.57]}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                  <group
                    position={[4.82, 21.05, 0.05]}
                    rotation={[0.22, 0.25, -1.57]}
                  >
                    <group position={[0, 10.55, 0]} rotation={[0.24, 0, -0.53]}>
                      <group position={[-0.01, 27.69, 0]}>
                        <group
                          position={[0, 23.94, 0]}
                          rotation={[-0.06, 0, -0.02]}
                        >
                          <group
                            position={[0.3, 7.85, -1.28]}
                            rotation={[0.1, 0.01, 0.01]}
                          >
                            <group
                              position={[0, 2.66, 0]}
                              rotation={[-0.03, -0.01, -0.07]}
                            />
                          </group>
                          <group
                            position={[0, 7.9, 0]}
                            rotation={[0.06, 0.01, 0.06]}
                          >
                            <group
                              position={[0, 3.69, 0]}
                              rotation={[-0.01, 0, -0.07]}
                            />
                          </group>
                          <group
                            position={[-0.4, 8.13, 1.25]}
                            rotation={[0.08, 0, 0.03]}
                          >
                            <group
                              position={[0, 3.94, 0]}
                              rotation={[-0.01, 0.01, -0.04]}
                            />
                          </group>
                          <group
                            position={[-0.24, 8.12, 2.75]}
                            rotation={[0.04, 0, 0.03]}
                          >
                            <group
                              position={[0, 3.52, 0]}
                              rotation={[0.03, 0.01, -0.06]}
                            />
                          </group>
                          <group
                            position={[0.54, 1.81, 2.03]}
                            rotation={[0.78, -0.23, -0.05]}
                          >
                            <group
                              position={[0, 4.97, 0]}
                              rotation={[-0.29, -0.03, 0.15]}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group
                    position={[9.9, 6, 11.05]}
                    rotation={[-1.36, 0, Math.PI]}
                  />
                  <group
                    position={[-9.9, 6, 11.05]}
                    rotation={[-1.36, 0, Math.PI]}
                  />
                  <group
                    position={[-4.82, 21.05, 0.05]}
                    rotation={[0.22, -0.25, 1.57]}
                  >
                    <group position={[0, 10.55, 0]} rotation={[0.24, 0, 0.53]}>
                      <group position={[0.01, 27.69, 0]}>
                        <group
                          position={[0, 23.94, 0]}
                          rotation={[-0.06, 0, 0.02]}
                        >
                          <group
                            position={[0, 7.9, 0]}
                            rotation={[0.06, -0.01, -0.06]}
                          >
                            <group
                              position={[0, 3.69, 0]}
                              rotation={[-0.01, 0, 0.07]}
                            />
                          </group>
                          <group
                            position={[0.4, 8.13, 1.25]}
                            rotation={[0.08, 0, -0.03]}
                          >
                            <group
                              position={[0, 3.94, 0]}
                              rotation={[-0.01, -0.01, 0.04]}
                            />
                          </group>
                          <group
                            position={[-0.54, 1.81, 2.03]}
                            rotation={[0.78, 0.23, 0.05]}
                          >
                            <group
                              position={[0, 4.97, 0]}
                              rotation={[-0.29, 0.03, -0.15]}
                            />
                          </group>
                          <group
                            position={[0.24, 8.12, 2.75]}
                            rotation={[0.04, 0, -0.03]}
                          >
                            <group
                              position={[0, 3.52, 0]}
                              rotation={[0.03, -0.01, 0.06]}
                            />
                          </group>
                          <group
                            position={[-0.3, 7.85, -1.28]}
                            rotation={[0.1, -0.01, -0.01]}
                          >
                            <group
                              position={[0, 2.66, 0]}
                              rotation={[-0.03, 0.01, 0.07]}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <mesh
          geometry={nodes.HS_M_Suit_L.geometry}
          material={materials.HS_M_Suit_L}
        />
      </group>
      <group scale={0.01}>
        <mesh
          geometry={nodes.Ramesses_M_Cuirass_H_primitive0.geometry}
          material={materials.Belt_B125}
        />
        <mesh
          geometry={nodes.Ramesses_M_Cuirass_H_primitive1.geometry}
          material={materials.Cuirass_B126}
        />
        <mesh
          geometry={nodes.Ramesses_M_Cuirass_H_primitive2.geometry}
          material={materials.Spoulders_B127}
        />
        <mesh
          geometry={nodes.Ramesses_M_Cuirass_H_primitive3.geometry}
          material={materials.Lames_B128}
        />
        <mesh
          geometry={nodes.Ramesses_M_Cuirass_H_primitive4.geometry}
          material={materials.Straps_B129}
        />
        <mesh
          geometry={nodes.Ramesses_M_Cuirass_H_primitive5.geometry}
          material={materials.Plates_B130}
        />
        <mesh
          geometry={nodes.Ramesses_M_Cuirass_H_primitive6.geometry}
          material={materials.Collar_B134}
        />
        <mesh
          geometry={nodes.Ramesses_M_Cuirass_H_primitive7.geometry}
          material={materials.Bracers_B135}
        />
        <mesh
          geometry={nodes.Ramesses_M_Cuirass_H_primitive8.geometry}
          material={materials.Frames_B136}
        />
        <mesh
          geometry={nodes.Ramesses_M_Cuirass_H_primitive9.geometry}
          material={materials.Tunic_B137}
        />
        <mesh
          geometry={nodes.Ramesses_M_Headress_H_primitive0.geometry}
          material={materials.Headress_B138}
        />
        <mesh
          geometry={nodes.Ramesses_M_Headress_H_primitive1.geometry}
          material={materials.Beard_B139}
        />
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[0, 2.67, 102.17]} rotation={[1.57, 0, 0]}>
            <group rotation={[0.23, 0, 0]}>
              <group
                position={[9.05, -1.84, -0.78]}
                rotation={[-0.19, 0, 3.12]}
              >
                <group position={[0, 43.55, 0]} rotation={[0.03, 0, 0]}>
                  <group
                    position={[0, 43.27, 0]}
                    rotation={[1.25, -0.02, 0.11]}
                  >
                    <group
                      position={[0, 13.43, 0]}
                      rotation={[0.27, 0.05, -0.04]}
                    />
                  </group>
                </group>
              </group>
              <group
                position={[-9.05, -1.84, -0.78]}
                rotation={[-0.19, 0, -3.12]}
              >
                <group position={[0, 43.55, 0]} rotation={[0.03, 0, 0]}>
                  <group
                    position={[0, 43.27, 0]}
                    rotation={[1.25, 0.02, -0.11]}
                  >
                    <group
                      position={[0, 13.43, 0]}
                      rotation={[0.27, -0.05, 0.04]}
                    />
                  </group>
                </group>
              </group>
            </group>
            <group position={[0, 7.12, 1.64]} rotation={[0.27, 0, 0]}>
              <group position={[0, 4.09, 0]} rotation={[-0.38, 0, 0]}>
                <group position={[0, 13.33, 0]} rotation={[-0.11, 0, 0]}>
                  <group position={[0, 26.71, 0]} rotation={[0.44, 0, 0]}>
                    <group position={[0, 3.75, 0]} rotation={[0.04, 0, 0]}>
                      <group position={[0, 3.56, 0]} rotation={[-0.26, 0, 0]}>
                        <group rotation={[1.57, Math.PI / 2, 0]}>
                          <group
                            position={[1.16, 2.38, 0]}
                            rotation={[0, 0, 1.57]}
                          >
                            <group
                              position={[3.01, 0.9, 0]}
                              rotation={[0, 0, 0.11]}
                            >
                              <group
                                position={[1.06, 0, 0]}
                                rotation={[0, 0, 0.18]}
                              />
                            </group>
                          </group>
                          <group
                            position={[2.63, 6.31, 0]}
                            rotation={[0, 0, 1.57]}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                  <group
                    position={[4.82, 21.05, 0.05]}
                    rotation={[0.22, 0.25, -1.57]}
                  >
                    <group position={[0, 10.55, 0]} rotation={[0.24, 0, -0.53]}>
                      <group position={[-0.01, 27.69, 0]}>
                        <group
                          position={[0, 23.94, 0]}
                          rotation={[-0.06, 0, -0.02]}
                        >
                          <group
                            position={[0.3, 7.85, -1.28]}
                            rotation={[0.1, 0.01, 0.01]}
                          >
                            <group
                              position={[0, 2.66, 0]}
                              rotation={[-0.03, -0.01, -0.07]}
                            />
                          </group>
                          <group
                            position={[0, 7.9, 0]}
                            rotation={[0.06, 0.01, 0.06]}
                          >
                            <group
                              position={[0, 3.69, 0]}
                              rotation={[-0.01, 0, -0.07]}
                            />
                          </group>
                          <group
                            position={[-0.4, 8.13, 1.25]}
                            rotation={[0.08, 0, 0.03]}
                          >
                            <group
                              position={[0, 3.94, 0]}
                              rotation={[-0.01, 0.01, -0.04]}
                            />
                          </group>
                          <group
                            position={[-0.24, 8.12, 2.75]}
                            rotation={[0.04, 0, 0.03]}
                          >
                            <group
                              position={[0, 3.52, 0]}
                              rotation={[0.03, 0.01, -0.06]}
                            />
                          </group>
                          <group
                            position={[0.54, 1.81, 2.03]}
                            rotation={[0.78, -0.23, -0.05]}
                          >
                            <group
                              position={[0, 4.97, 0]}
                              rotation={[-0.29, -0.03, 0.15]}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group
                    position={[9.9, 6, 11.05]}
                    rotation={[-1.36, 0, Math.PI]}
                  />
                  <group
                    position={[-9.9, 6, 11.05]}
                    rotation={[-1.36, 0, Math.PI]}
                  />
                  <group
                    position={[-4.82, 21.05, 0.05]}
                    rotation={[0.22, -0.25, 1.57]}
                  >
                    <group position={[0, 10.55, 0]} rotation={[0.24, 0, 0.53]}>
                      <group position={[0.01, 27.69, 0]}>
                        <group
                          position={[0, 23.94, 0]}
                          rotation={[-0.06, 0, 0.02]}
                        >
                          <group
                            position={[0, 7.9, 0]}
                            rotation={[0.06, -0.01, -0.06]}
                          >
                            <group
                              position={[0, 3.69, 0]}
                              rotation={[-0.01, 0, 0.07]}
                            />
                          </group>
                          <group
                            position={[0.4, 8.13, 1.25]}
                            rotation={[0.08, 0, -0.03]}
                          >
                            <group
                              position={[0, 3.94, 0]}
                              rotation={[-0.01, -0.01, 0.04]}
                            />
                          </group>
                          <group
                            position={[-0.54, 1.81, 2.03]}
                            rotation={[0.78, 0.23, 0.05]}
                          >
                            <group
                              position={[0, 4.97, 0]}
                              rotation={[-0.29, 0.03, -0.15]}
                            />
                          </group>
                          <group
                            position={[0.24, 8.12, 2.75]}
                            rotation={[0.04, 0, -0.03]}
                          >
                            <group
                              position={[0, 3.52, 0]}
                              rotation={[0.03, -0.01, 0.06]}
                            />
                          </group>
                          <group
                            position={[-0.3, 7.85, -1.28]}
                            rotation={[0.1, -0.01, -0.01]}
                          >
                            <group
                              position={[0, 2.66, 0]}
                              rotation={[-0.03, 0.01, 0.07]}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <mesh
          geometry={nodes.Ramesses_M_Pants_L.geometry}
          material={materials.Ramesses_M_Pants_L_B140}
        />
        <mesh
          geometry={nodes.Ramesses_M_Pouldrons_L.geometry}
          material={materials.Ramesses_M_Pouldrons_L_B141}
        />
      </group>
      <group scale={0.01}>
        <mesh
          geometry={nodes.CC_Base_Body_primitive0.geometry}
          material={materials.Std_Skin_Head_B100}
        />
        <mesh
          geometry={nodes.CC_Base_Body_primitive1.geometry}
          material={materials.Std_Skin_Body_B101}
        />
        <mesh
          geometry={nodes.CC_Base_Body_primitive2.geometry}
          material={materials.Std_Skin_Arm_B102}
        />
        <mesh
          geometry={nodes.CC_Base_Body_primitive3.geometry}
          material={materials.Std_Skin_Leg_B103}
        />
        <mesh
          geometry={nodes.CC_Base_Body_primitive4.geometry}
          material={materials.Std_Nails_B104}
        />
        <mesh
          geometry={nodes.CC_Base_Body_primitive5.geometry}
          material={materials.Std_Eyelash_B105}
        />
      </group>
      <group scale={0.01}>
        <mesh
          geometry={nodes.CC_Base_Eye_primitive0.geometry}
          material={materials.Std_Eye_R_B120}
        />
        <mesh
          geometry={nodes.CC_Base_Eye_primitive1.geometry}
          material={materials.Std_Cornea_R_B121}
        />
        <mesh
          geometry={nodes.CC_Base_Eye_primitive2.geometry}
          material={materials.Std_Eye_L_B122}
        />
        <mesh
          geometry={nodes.CC_Base_Eye_primitive3.geometry}
          material={materials.Std_Cornea_L_B123}
        />
      </group>
      <group scale={0.01}>
        <mesh
          geometry={nodes.CC_Base_EyeOcclusion_primitive0.geometry}
          material={materials.Std_Eye_Occlusion_R_B118}
        />
        <mesh
          geometry={nodes.CC_Base_EyeOcclusion_primitive1.geometry}
          material={materials.Std_Eye_Occlusion_L_B119}
        />
      </group>
      <group scale={0.01}>
        <mesh
          geometry={nodes.CC_Base_TearLine_primitive0.geometry}
          material={materials.Std_Tearline_R_B108}
        />
        <mesh
          geometry={nodes.CC_Base_TearLine_primitive1.geometry}
          material={materials.Std_Tearline_L_B109}
        />
      </group>
      <group scale={0.01}>
        <mesh
          geometry={nodes.CC_Base_Teeth_primitive0.geometry}
          material={materials.Std_Upper_Teeth_B111}
        />
        <mesh
          geometry={nodes.CC_Base_Teeth_primitive1.geometry}
          material={materials.Std_Lower_Teeth_B112}
        />
      </group>
      <group scale={0.01}>
        <mesh
          geometry={nodes.Double_high_primitive0.geometry}
          material={materials.Scalp_Transparency_B115}
        />
        <mesh
          geometry={nodes.Double_high_primitive1.geometry}
          material={materials["Hair_Transparency.003_B116"]}
        />
      </group>
      <group scale={0.01}>
        <mesh
          geometry={nodes.HG_Body_003_primitive0.geometry}
          material={materials.Tech_2}
        />
        <mesh
          geometry={nodes.HG_Body_003_primitive1.geometry}
          material={materials.Armor_Plates}
        />
        <mesh
          geometry={nodes.HG_Body_003_primitive2.geometry}
          material={materials.Under_Plates}
        />
        <mesh
          geometry={nodes.HG_Body_003_primitive3.geometry}
          material={materials.Copper}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0.05, 1.6]} rotation={[0, 0, Math.PI]}>
          <group
            position={[0, 0.25, 0.07]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
          />
        </group>
        <group position={[0, 0.03, 1.02]} rotation={[1.8, 0, 0]}>
          <group position={[0, 0.07, 0]} rotation={[0.05, 0, 0]}>
            <group position={[0, 0.04, 0]} rotation={[-0.38, 0, 0]}>
              <group position={[0, 0.13, 0]} rotation={[-0.11, 0, 0]}>
                <group position={[0, 0.27, 0]} rotation={[0.44, 0, 0]}>
                  <group position={[0, 0.04, 0]} rotation={[0.04, 0, 0]} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
      <group position={[0, 1.06, -0.02]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, -0.02, 0.07]}>
          <group rotation={[1.84, 0, 0]}>
            <group position={[0, -0.04, 0]} rotation={[-1.84, 0, 0]}>
              <group rotation={[1.8, 0, 0]}>
                <group position={[0, -0.07, 0]}>
                  <group rotation={[0, -1.08, 0]} />
                  <group
                    position={[0.09, -0.02, -0.01]}
                    rotation={[2.93, 0, 0.02]}
                  >
                    <group position={[0, 0.44, 0]} rotation={[0, 0, 0]}>
                      <group
                        position={[0, 0.45, 0]}
                        rotation={[-1.3, 0.05, -0.11]}
                      />
                      <group position={[0, 0.23, 0]} rotation={[0, -0.02, 0]} />
                    </group>
                    <group position={[0, 0.22, 0]} />
                  </group>
                  <group
                    position={[-0.09, -0.02, -0.01]}
                    rotation={[2.93, 0, -0.02]}
                  >
                    <group position={[0, 0.44, 0]} rotation={[0, 0, 0]}>
                      <group
                        position={[0, 0.45, 0]}
                        rotation={[-1.3, -0.05, 0.11]}
                      />
                      <group position={[0, 0.23, 0]} rotation={[0, 0.02, 0]} />
                    </group>
                    <group position={[0, 0.22, 0]} />
                  </group>
                  <group
                    position={[0.09, -0.02, -0.01]}
                    rotation={[-1.8, 0, 0]}
                  >
                    <group rotation={[-1.55, 0, 0.02]}>
                      <group position={[0, 0.44, 0]} rotation={[0, 0, 0]}>
                        <group
                          position={[0, 0.45, 0]}
                          rotation={[-1.3, 0.05, -0.11]}
                        >
                          <group
                            position={[0, 0.13, 0]}
                            rotation={[2.87, 0.06, 3.12]}
                          />
                        </group>
                      </group>
                    </group>
                    <group rotation={[-1.55, 0, 0.02]} />
                  </group>
                  <group
                    position={[0.09, -0.02, -0.01]}
                    rotation={[2.93, 0, 0.02]}
                  />
                  <group
                    position={[0.09, -0.02, -0.01]}
                    rotation={[2.93, 0, 0.02]}
                  >
                    <group position={[0, 0.22, 0]}>
                      <group position={[0, 0.22, 0]} rotation={[0, 0, 0]}>
                        <group position={[0, 0.23, 0]}>
                          <group
                            position={[0, 0.23, 0]}
                            rotation={[-1.3, 0.05, -0.11]}
                          >
                            <group
                              position={[0, 0.13, 0]}
                              rotation={[2.87, 0.06, 3.12]}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group
                    position={[-0.09, -0.02, -0.01]}
                    rotation={[-1.8, 0, 0]}
                  >
                    <group rotation={[-1.55, 0, -0.02]}>
                      <group position={[0, 0.44, 0]} rotation={[0, 0, 0]}>
                        <group
                          position={[0, 0.45, 0]}
                          rotation={[-1.3, -0.05, 0.11]}
                        >
                          <group
                            position={[0, 0.13, 0]}
                            rotation={[2.87, -0.06, -3.12]}
                          />
                        </group>
                      </group>
                    </group>
                    <group rotation={[-1.55, 0, -0.02]} />
                  </group>
                  <group
                    position={[-0.09, -0.02, -0.01]}
                    rotation={[2.93, 0, -0.02]}
                  />
                  <group
                    position={[-0.09, -0.02, -0.01]}
                    rotation={[2.93, 0, -0.02]}
                  >
                    <group position={[0, 0.22, 0]}>
                      <group position={[0, 0.22, 0]} rotation={[0, 0, 0]}>
                        <group position={[0, 0.23, 0]}>
                          <group
                            position={[0, 0.23, 0]}
                            rotation={[-1.3, -0.05, 0.11]}
                          >
                            <group
                              position={[0, 0.13, 0]}
                              rotation={[2.87, -0.06, -3.12]}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group rotation={[0.05, 0, 0]} />
              </group>
            </group>
          </group>
        </group>
        <group position={[0, -0.02, 0.07]}>
          <group rotation={[1.46, 0, 0]}>
            <group rotation={[0.38, 0, 0]}>
              <group rotation={[-0.38, 0, 0]} />
            </group>
            <group position={[0, 0.13, 0]} rotation={[-1.46, 0, 0]}>
              <group rotation={[1.36, 0, 0]}>
                <group position={[0, 0.27, 0]} rotation={[0.44, 0, 0]}>
                  <group position={[0, 0.04, 0]} rotation={[0.04, 0, 0]}>
                    <group position={[0, 0.04, 0]} rotation={[-0.26, 0, 0]}>
                      <group rotation={[-Math.PI / 2, 0, Math.PI]}>
                        <group
                          position={[0, 0.1, 0.03]}
                          rotation={[0, 0, -Math.PI]}
                        />
                        <group
                          position={[0, 0.09, 0]}
                          rotation={[0, 0, Math.PI]}
                        />
                        <group position={[-0.03, 0.07, 0.07]}>
                          <group
                            position={[-0.02, 0.01, 0.01]}
                            rotation={[-1.57, 0.34, Math.PI]}
                          />
                          <group
                            position={[-0.01, 0.02, 0.01]}
                            rotation={[-1.57, 0.24, Math.PI]}
                          />
                          <group
                            position={[0, 0.02, 0.01]}
                            rotation={[-1.57, 0.19, Math.PI]}
                          />
                          <group
                            position={[0.01, 0.02, 0]}
                            rotation={[-1.57, 0.17, Math.PI]}
                          />
                          <group
                            position={[0.01, 0.02, -0.01]}
                            rotation={[-1.57, 0.22, Math.PI]}
                          />
                          <group
                            position={[0.01, 0.02, -0.01]}
                            rotation={[-1.57, 0.09, Math.PI]}
                          />
                          <group
                            position={[0, 0.02, -0.01]}
                            rotation={[-1.57, 0.11, Math.PI]}
                          />
                          <group
                            position={[-0.01, 0.02, 0]}
                            rotation={[-1.57, 0.08, Math.PI]}
                          />
                          <group
                            position={[-0.01, 0.01, 0]}
                            rotation={[-1.57, 0.44, Math.PI]}
                          />
                          <group
                            position={[-0.01, 0.02, 0]}
                            rotation={[-1.57, 0.17, Math.PI]}
                          />
                          <group
                            position={[0, 0.02, 0]}
                            rotation={[-1.57, 0.19, Math.PI]}
                          />
                          <group
                            position={[0.01, 0.02, 0]}
                            rotation={[-1.57, 0.05, Math.PI]}
                          />
                          <group rotation={[0.29, 0.62, -0.85]} />
                          <group rotation={[1.11, 1.27, -1.4]} />
                          <group rotation={[2.52, -1.14, 2.74]} />
                          <group rotation={[0.1, -0.32, 0.58]} />
                          <group rotation={[-0.09, 0.21, 0.8]} />
                          <group rotation={[-0.32, 0.95, 0.61]} />
                          <group rotation={[-2.97, -0.43, -3.1]} />
                          <group rotation={[0.01, 0.06, -0.47]} />
                        </group>
                        <group position={[0.03, 0.07, 0.07]}>
                          <group
                            position={[0.02, 0.01, 0.01]}
                            rotation={[-1.57, -0.34, Math.PI]}
                          />
                          <group
                            position={[0.01, 0.02, 0.01]}
                            rotation={[-1.57, -0.24, -Math.PI]}
                          />
                          <group
                            position={[0, 0.02, 0.01]}
                            rotation={[-1.57, -0.19, -Math.PI]}
                          />
                          <group
                            position={[-0.01, 0.02, 0]}
                            rotation={[-1.57, -0.17, -Math.PI]}
                          />
                          <group
                            position={[-0.01, 0.02, -0.01]}
                            rotation={[-1.57, -0.22, -Math.PI]}
                          />
                          <group
                            position={[-0.01, 0.02, -0.01]}
                            rotation={[-1.57, -0.09, -Math.PI]}
                          />
                          <group
                            position={[0, 0.02, -0.01]}
                            rotation={[-1.57, -0.11, -Math.PI]}
                          />
                          <group
                            position={[0.01, 0.02, 0]}
                            rotation={[-1.57, -0.08, -Math.PI]}
                          />
                          <group
                            position={[0.01, 0.01, 0]}
                            rotation={[-1.57, -0.44, Math.PI]}
                          />
                          <group
                            position={[0.01, 0.02, 0]}
                            rotation={[-1.57, -0.17, -Math.PI]}
                          />
                          <group
                            position={[0, 0.02, 0]}
                            rotation={[-1.57, -0.19, -Math.PI]}
                          />
                          <group
                            position={[-0.01, 0.02, 0]}
                            rotation={[-1.57, -0.05, -Math.PI]}
                          />
                          <group rotation={[0.28, -0.61, 0.85]} />
                          <group rotation={[1.04, -1.26, 1.33]} />
                          <group rotation={[2.55, 1.12, -2.76]} />
                          <group rotation={[0.09, 0.32, -0.57]} />
                          <group rotation={[-0.09, -0.21, -0.8]} />
                          <group rotation={[-0.34, -0.97, -0.62]} />
                          <group rotation={[-2.97, 0.48, 3.1]} />
                          <group rotation={[0.01, -0.05, 0.47]} />
                        </group>
                        <group
                          position={[-0.07, 0.01, 0.04]}
                          rotation={[-1.28, 0.17, 2.97]}
                        >
                          <group
                            position={[0, 0.04, -0.02]}
                            rotation={[0.24, 0.4, 0.12]}
                          />
                          <group
                            position={[0, 0, -0.02]}
                            rotation={[0.24, 0.44, 0.13]}
                          />
                          <group
                            position={[0, -0.02, -0.01]}
                            rotation={[0.17, 0.8, 0.17]}
                          />
                        </group>
                        <group
                          position={[0.07, 0.01, 0.04]}
                          rotation={[-1.28, -0.17, -2.97]}
                        >
                          <group
                            position={[0, 0.04, -0.02]}
                            rotation={[0.24, -0.4, -0.12]}
                          />
                          <group
                            position={[0, 0, -0.02]}
                            rotation={[0.24, -0.44, -0.13]}
                          />
                          <group
                            position={[0, -0.02, -0.01]}
                            rotation={[0.17, -0.8, -0.17]}
                          />
                        </group>
                        <group
                          position={[0, 0.02, 0.01]}
                          rotation={[2.49, 0, -Math.PI]}
                        >
                          <group
                            position={[0, 0.03, -0.02]}
                            rotation={[-0.45, 0, 0]}
                          >
                            <group
                              position={[0, 0.02, 0]}
                              rotation={[-1.77, 0, 0]}
                            />
                          </group>
                          <group
                            position={[0, 0.08, 0]}
                            rotation={[-2.22, 0, 0]}
                          >
                            <group position={[0, 0.02, 0.01]} />
                          </group>
                          <group
                            position={[0.03, 0.06, 0]}
                            rotation={[-2.22, -0.27, 0]}
                          />
                          <group
                            position={[-0.03, 0.06, 0]}
                            rotation={[-2.22, 0.27, 0]}
                          />
                          <group
                            position={[0, 0.05, 0.03]}
                            rotation={[-2.22, 0, 0]}
                          />
                          <group
                            position={[0.05, 0.04, 0]}
                            rotation={[-2.22, 0.42, 0]}
                          />
                          <group
                            position={[-0.05, 0.04, 0]}
                            rotation={[-2.22, -0.42, 0]}
                          />
                          <group
                            position={[0, 0.03, -0.02]}
                            rotation={[-0.45, 0, 0]}
                          >
                            <group rotation={[-1.77, 0, 0]} />
                          </group>
                          <group
                            position={[0, 0.03, -0.02]}
                            rotation={[-0.45, 0, 0]}
                          >
                            <group
                              position={[0, -0.02, 0.01]}
                              rotation={[-1.77, 0, 0]}
                            />
                          </group>
                        </group>
                        <group
                          position={[-0.06, 0.07, 0.07]}
                          rotation={[-Math.PI / 2, -0.01, Math.PI]}
                        />
                        <group
                          position={[-0.06, 0.07, 0.08]}
                          rotation={[-Math.PI / 2, -0.34, Math.PI]}
                        />
                        <group
                          position={[-0.04, 0.09, 0.09]}
                          rotation={[-Math.PI / 2, -0.27, Math.PI]}
                        />
                        <group
                          position={[-0.02, 0.1, 0.08]}
                          rotation={[-Math.PI / 2, -0.15, Math.PI]}
                        />
                        <group
                          position={[0.06, 0.07, 0.07]}
                          rotation={[-Math.PI / 2, 0.01, Math.PI]}
                        />
                        <group
                          position={[0.06, 0.07, 0.08]}
                          rotation={[-Math.PI / 2, 0.34, -Math.PI]}
                        />
                        <group
                          position={[0.04, 0.09, 0.09]}
                          rotation={[-Math.PI / 2, 0.27, -Math.PI]}
                        />
                        <group
                          position={[0.02, 0.1, 0.08]}
                          rotation={[-Math.PI / 2, 0.14, -Math.PI]}
                        />
                        <group
                          position={[-0.06, 0.02, 0.01]}
                          rotation={[-Math.PI / 2, -0.23, Math.PI]}
                        />
                        <group
                          position={[0.06, 0.02, 0.01]}
                          rotation={[-Math.PI / 2, 0.23, Math.PI]}
                        />
                        <group
                          position={[0, 0.1, 0.07]}
                          rotation={[-Math.PI / 2, 0, Math.PI]}
                        />
                        <group
                          position={[-0.02, 0.09, 0.05]}
                          rotation={[-Math.PI / 2, -0.11, Math.PI]}
                        />
                        <group
                          position={[0.02, 0.09, 0.05]}
                          rotation={[-Math.PI / 2, 0.11, Math.PI]}
                        />
                        <group
                          position={[0, 0.02, 0.01]}
                          rotation={[2.49, 0, -Math.PI]}
                        >
                          <group
                            position={[0, 0.07, -0.03]}
                            rotation={[-2.22, -0.03, 0]}
                          />
                        </group>
                        <group
                          position={[0, 0.02, 0.01]}
                          rotation={[2.49, 0, -Math.PI]}
                        >
                          <group
                            position={[0.01, 0.07, -0.03]}
                            rotation={[-2.22, -0.02, 0]}
                          />
                          <group
                            position={[-0.01, 0.07, -0.03]}
                            rotation={[-2.22, 0.02, 0]}
                          />
                        </group>
                        <group
                          position={[0, 0.02, 0.01]}
                          rotation={[2.49, 0, -Math.PI]}
                        >
                          <group
                            position={[0.06, 0.03, -0.04]}
                            rotation={[-2.22, -0.09, 0]}
                          />
                          <group
                            position={[-0.06, 0.03, -0.04]}
                            rotation={[-2.22, 0.09, 0]}
                          />
                          <group
                            position={[0.03, 0.06, -0.03]}
                            rotation={[-2.22, 0.06, 0]}
                          />
                          <group
                            position={[-0.03, 0.06, -0.03]}
                            rotation={[-2.22, -0.06, 0]}
                          />
                        </group>
                        <group
                          position={[0, 0.02, 0.01]}
                          rotation={[2.49, 0, -Math.PI]}
                        >
                          <group
                            position={[0.02, 0.06, -0.04]}
                            rotation={[-2.22, 0.06, 0]}
                          />
                          <group
                            position={[-0.02, 0.06, -0.04]}
                            rotation={[-2.22, -0.06, 0]}
                          />
                          <group
                            position={[0, 0.07, -0.05]}
                            rotation={[-2.22, 0.07, 0]}
                          />
                        </group>
                        <group
                          position={[0, 0.02, 0.01]}
                          rotation={[2.49, 0, -Math.PI]}
                        >
                          <group
                            position={[0, 0.06, -0.06]}
                            rotation={[2.49, 0, Math.PI]}
                          >
                            <group
                              position={[0, 0.02, 0.01]}
                              rotation={[-Math.PI / 2, 0, -Math.PI]}
                            >
                              <group position={[0, 0.01, -0.01]} />
                              <group position={[0, -0.01, -0.01]} />
                            </group>
                            <group rotation={[-Math.PI / 2, 0, -Math.PI]} />
                            <group
                              position={[-0.02, -0.01, 0.01]}
                              rotation={[-Math.PI / 2, -0.29, -Math.PI]}
                            />
                            <group
                              position={[0.02, -0.01, 0.01]}
                              rotation={[-Math.PI / 2, 0.29, -Math.PI]}
                            />
                          </group>
                          <group
                            position={[0.04, 0.03, -0.07]}
                            rotation={[-2.22, -0.57, 0]}
                          />
                          <group
                            position={[-0.04, 0.03, -0.07]}
                            rotation={[-2.22, 0.57, 0]}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group position={[0, 0.27, 0]} rotation={[-1.36, 0, 0]}>
                  <group rotation={[1.82, 0, 0]}>
                    <group position={[0, 0.07, 0]} rotation={[-1.82, 0, 0]} />
                    <group position={[0, 0.04, 0]} />
                  </group>
                </group>
                <group
                  position={[0.05, 0.21, 0]}
                  rotation={[-1.36, -0.01, -1.33]}
                >
                  <group position={[0, 0.11, 0]} rotation={[1.56, 1.34, -2.09]}>
                    <group position={[0, 0.28, 0]} rotation={[0.01, 0, 0]}>
                      <group
                        position={[0, 0.24, 0]}
                        rotation={[-0.06, 0, -0.02]}
                      />
                      <group position={[0, 0.12, 0]} />
                    </group>
                    <group position={[0, 0.14, 0]} />
                  </group>
                  <group position={[0, 0.11, 0]} rotation={[-0.01, 0, 1.33]}>
                    <group rotation={[1.57, 0.01, -2.1]}>
                      <group position={[0, 0.28, 0]} rotation={[0.01, 0, 0]}>
                        <group
                          position={[0, 0.24, 0]}
                          rotation={[-0.06, 0, -0.02]}
                        />
                      </group>
                    </group>
                    <group rotation={[1.57, 0.01, -2.1]} />
                  </group>
                  <group
                    position={[0, 0.11, 0]}
                    rotation={[1.56, 1.34, -2.09]}
                  />
                  <group position={[0, 0.11, 0]} rotation={[1.56, 1.34, -2.09]}>
                    <group position={[0, 0.14, 0]}>
                      <group position={[0, 0.14, 0]} rotation={[0.01, 0, 0]}>
                        <group position={[0, 0.12, 0]}>
                          <group
                            position={[0, 0.12, 0]}
                            rotation={[-0.06, 0, -0.02]}
                          >
                            <group
                              position={[0, 0.03, 0.01]}
                              rotation={[-2.66, 1.4, 2.99]}
                            >
                              <group
                                position={[0, 0.06, 0]}
                                rotation={[-0.2, -0.7, -0.38]}
                              >
                                <group
                                  position={[0, 0.04, 0]}
                                  rotation={[0.06, 0, -0.01]}
                                />
                              </group>
                              <group
                                position={[-0.01, -0.01, 0]}
                                rotation={[-1.99, 1.06, 1.95]}
                              >
                                <group
                                  position={[0, 0.05, 0]}
                                  rotation={[0.32, 0, 0.03]}
                                />
                              </group>
                              <group
                                position={[0, 0.06, 0]}
                                rotation={[-0.2, -0.7, -0.38]}
                              >
                                <group
                                  position={[0, 0.04, 0]}
                                  rotation={[0.06, 0, -0.01]}
                                />
                              </group>
                              <group
                                position={[-0.01, -0.01, 0]}
                                rotation={[-1.99, 1.06, 1.95]}
                              >
                                <group
                                  position={[0, 0.05, 0]}
                                  rotation={[0.32, 0, 0.03]}
                                />
                              </group>
                              <group
                                position={[0, 0.06, 0]}
                                rotation={[-0.2, -0.7, -0.38]}
                              >
                                <group
                                  position={[0, 0.04, 0]}
                                  rotation={[0.06, 0, -0.01]}
                                >
                                  <group
                                    position={[0, 0.02, 0]}
                                    rotation={[-0.04, 0, 0.03]}
                                  />
                                </group>
                              </group>
                              <group
                                position={[-0.01, -0.01, 0]}
                                rotation={[-1.99, 1.06, 1.95]}
                              >
                                <group
                                  position={[0, 0.05, 0]}
                                  rotation={[0.32, 0, 0.03]}
                                >
                                  <group
                                    position={[0, 0.03, 0]}
                                    rotation={[0.13, 0, -0.07]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              position={[0, 0.03, 0]}
                              rotation={[-2.35, 1.49, 2.5]}
                            >
                              <group
                                position={[0, 0.05, 0]}
                                rotation={[0.03, 0.1, -0.08]}
                              >
                                <group
                                  position={[0, 0.04, 0]}
                                  rotation={[0.04, 0, 0]}
                                />
                              </group>
                              <group
                                position={[0, 0.05, 0]}
                                rotation={[0.03, 0.1, -0.08]}
                              >
                                <group
                                  position={[0, 0.04, 0]}
                                  rotation={[0.04, 0, 0]}
                                />
                              </group>
                              <group
                                position={[0, 0.05, 0]}
                                rotation={[0.03, 0.1, -0.08]}
                              >
                                <group
                                  position={[0, 0.04, 0]}
                                  rotation={[0.04, 0, 0]}
                                >
                                  <group
                                    position={[0, 0.03, 0]}
                                    rotation={[-0.01, 0, 0.01]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              position={[0, 0.03, 0]}
                              rotation={[0, 1.54, 0]}
                            >
                              <group
                                position={[0, 0.05, 0]}
                                rotation={[-0.09, 0.45, 0.07]}
                              >
                                <group
                                  position={[0, 0.04, 0]}
                                  rotation={[0.07, 0, 0.02]}
                                />
                              </group>
                              <group
                                position={[0, 0.05, 0]}
                                rotation={[-0.09, 0.45, 0.07]}
                              >
                                <group
                                  position={[0, 0.04, 0]}
                                  rotation={[0.07, 0, 0.02]}
                                />
                              </group>
                              <group
                                position={[0, 0.05, 0]}
                                rotation={[-0.09, 0.45, 0.07]}
                              >
                                <group
                                  position={[0, 0.04, 0]}
                                  rotation={[0.07, 0, 0.02]}
                                >
                                  <group
                                    position={[0, 0.02, 0]}
                                    rotation={[-0.06, 0, -0.04]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              position={[0, 0.03, 0]}
                              rotation={[0.12, 1.44, -0.28]}
                            >
                              <group
                                position={[0, 0.05, 0]}
                                rotation={[-1.2, 1.29, 1.2]}
                              >
                                <group
                                  position={[0, 0.03, 0]}
                                  rotation={[0.05, 0, 0.06]}
                                />
                              </group>
                              <group
                                position={[0, 0.05, 0]}
                                rotation={[-1.2, 1.29, 1.2]}
                              >
                                <group
                                  position={[0, 0.03, 0]}
                                  rotation={[0.05, 0, 0.06]}
                                />
                              </group>
                              <group
                                position={[0, 0.05, 0]}
                                rotation={[-1.2, 1.29, 1.2]}
                              >
                                <group
                                  position={[0, 0.03, 0]}
                                  rotation={[0.05, 0, 0.06]}
                                >
                                  <group
                                    position={[0, 0.01, 0]}
                                    rotation={[0.02, 0, -0.12]}
                                  />
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group
                  position={[-0.05, 0.21, 0]}
                  rotation={[-1.36, 0.01, 1.33]}
                >
                  <group position={[0, 0.11, 0]} rotation={[1.56, -1.34, 2.09]}>
                    <group position={[0, 0.28, 0]} rotation={[0.01, 0, 0]}>
                      <group
                        position={[0, 0.24, 0]}
                        rotation={[-0.06, 0, 0.02]}
                      />
                      <group position={[0, 0.12, 0]} />
                    </group>
                    <group position={[0, 0.14, 0]} />
                  </group>
                  <group position={[0, 0.11, 0]} rotation={[-0.01, 0, -1.33]}>
                    <group rotation={[1.57, -0.01, 2.1]}>
                      <group position={[0, 0.28, 0]} rotation={[0.01, 0, 0]}>
                        <group
                          position={[0, 0.24, 0]}
                          rotation={[-0.06, 0, 0.02]}
                        />
                      </group>
                    </group>
                    <group rotation={[1.57, -0.01, 2.1]} />
                  </group>
                  <group
                    position={[0, 0.11, 0]}
                    rotation={[1.56, -1.34, 2.09]}
                  />
                  <group position={[0, 0.11, 0]} rotation={[1.56, -1.34, 2.09]}>
                    <group position={[0, 0.14, 0]}>
                      <group position={[0, 0.14, 0]} rotation={[0.01, 0, 0]}>
                        <group position={[0, 0.12, 0]}>
                          <group
                            position={[0, 0.12, 0]}
                            rotation={[-0.06, 0, 0.02]}
                          >
                            <group
                              position={[0, 0.03, 0.01]}
                              rotation={[-2.66, -1.4, -2.99]}
                            >
                              <group
                                position={[0, 0.06, 0]}
                                rotation={[-0.2, 0.7, 0.38]}
                              >
                                <group
                                  position={[0, 0.04, 0]}
                                  rotation={[0.06, 0, 0.01]}
                                />
                              </group>
                              <group
                                position={[0.01, -0.01, 0]}
                                rotation={[-1.99, -1.06, -1.95]}
                              >
                                <group
                                  position={[0, 0.05, 0]}
                                  rotation={[0.32, 0, -0.03]}
                                />
                              </group>
                              <group
                                position={[0, 0.06, 0]}
                                rotation={[-0.2, 0.7, 0.38]}
                              >
                                <group
                                  position={[0, 0.04, 0]}
                                  rotation={[0.06, 0, 0.01]}
                                />
                              </group>
                              <group
                                position={[0.01, -0.01, 0]}
                                rotation={[-1.99, -1.06, -1.95]}
                              >
                                <group
                                  position={[0, 0.05, 0]}
                                  rotation={[0.32, 0, -0.03]}
                                />
                              </group>
                              <group
                                position={[0, 0.06, 0]}
                                rotation={[-0.2, 0.7, 0.38]}
                              >
                                <group
                                  position={[0, 0.04, 0]}
                                  rotation={[0.06, 0, 0.01]}
                                >
                                  <group
                                    position={[0, 0.02, 0]}
                                    rotation={[-0.04, 0, -0.03]}
                                  />
                                </group>
                              </group>
                              <group
                                position={[0.01, -0.01, 0]}
                                rotation={[-1.99, -1.06, -1.95]}
                              >
                                <group
                                  position={[0, 0.05, 0]}
                                  rotation={[0.32, 0, -0.03]}
                                >
                                  <group
                                    position={[0, 0.03, 0]}
                                    rotation={[0.13, 0, 0.07]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              position={[0, 0.03, 0]}
                              rotation={[-2.35, -1.49, -2.5]}
                            >
                              <group
                                position={[0, 0.05, 0]}
                                rotation={[0.03, -0.1, 0.08]}
                              >
                                <group
                                  position={[0, 0.04, 0]}
                                  rotation={[0.04, 0, 0]}
                                />
                              </group>
                              <group
                                position={[0, 0.05, 0]}
                                rotation={[0.03, -0.1, 0.08]}
                              >
                                <group
                                  position={[0, 0.04, 0]}
                                  rotation={[0.04, 0, 0]}
                                />
                              </group>
                              <group
                                position={[0, 0.05, 0]}
                                rotation={[0.03, -0.1, 0.08]}
                              >
                                <group
                                  position={[0, 0.04, 0]}
                                  rotation={[0.04, 0, 0]}
                                >
                                  <group
                                    position={[0, 0.03, 0]}
                                    rotation={[-0.01, 0, -0.01]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              position={[0, 0.03, 0]}
                              rotation={[0, -1.54, 0]}
                            >
                              <group
                                position={[0, 0.05, 0]}
                                rotation={[-0.09, -0.45, -0.07]}
                              >
                                <group
                                  position={[0, 0.04, 0]}
                                  rotation={[0.07, 0, -0.02]}
                                />
                              </group>
                              <group
                                position={[0, 0.05, 0]}
                                rotation={[-0.09, -0.45, -0.07]}
                              >
                                <group
                                  position={[0, 0.04, 0]}
                                  rotation={[0.07, 0, -0.02]}
                                />
                              </group>
                              <group
                                position={[0, 0.05, 0]}
                                rotation={[-0.09, -0.45, -0.07]}
                              >
                                <group
                                  position={[0, 0.04, 0]}
                                  rotation={[0.07, 0, -0.02]}
                                >
                                  <group
                                    position={[0, 0.02, 0]}
                                    rotation={[-0.06, 0, 0.04]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              position={[0, 0.03, 0]}
                              rotation={[0.12, -1.44, 0.28]}
                            >
                              <group
                                position={[0, 0.05, 0]}
                                rotation={[-1.2, -1.29, -1.2]}
                              >
                                <group
                                  position={[0, 0.03, 0]}
                                  rotation={[0.05, 0, -0.06]}
                                />
                              </group>
                              <group
                                position={[0, 0.05, 0]}
                                rotation={[-1.2, -1.29, -1.2]}
                              >
                                <group
                                  position={[0, 0.03, 0]}
                                  rotation={[0.05, 0, -0.06]}
                                />
                              </group>
                              <group
                                position={[0, 0.05, 0]}
                                rotation={[-1.2, -1.29, -1.2]}
                              >
                                <group
                                  position={[0, 0.03, 0]}
                                  rotation={[0.05, 0, -0.06]}
                                >
                                  <group
                                    position={[0, 0.01, 0]}
                                    rotation={[0.02, 0, 0.12]}
                                  />
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group
                  position={[0.1, 0.06, 0.13]}
                  rotation={[-1.36, 0, Math.PI]}
                >
                  <group position={[0, -0.02, 0]} />
                </group>
                <group
                  position={[-0.1, 0.06, 0.13]}
                  rotation={[-1.36, 0, Math.PI]}
                >
                  <group position={[0, -0.02, 0]} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
      <group position={[0.6, 1.21, -0.09]} rotation={[0.02, 0.06, -2.12]} />
      <group position={[0.39, 1.33, -0.6]} rotation={[-1.58, 1.04, -3.13]} />
      <group position={[-0.6, 1.21, -0.09]} rotation={[0.02, -0.06, 2.12]} />
      <group position={[-0.39, 1.33, -0.6]} rotation={[-1.58, -1.04, 3.13]} />
      <group position={[0.07, 0.12, -0.05]} rotation={[-Math.PI / 2, 0, 0.11]}>
        <group position={[0, -0.13, -0.04]}>
          <group position={[-0.02, 0.16, -0.01]}>
            <group position={[0.07, -0.01, 0]}>
              <group position={[-0.04, 0, 0]}>
                <group position={[-0.02, -0.16, 0.01]}>
                  <group
                    position={[0, 0.13, 0.04]}
                    rotation={[-2.85, 0.06, 0]}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
      <group position={[0.08, 0.55, 0.84]} rotation={[-1.55, 0, 0]} />
      <group
        position={[-0.07, 0.12, -0.05]}
        rotation={[-Math.PI / 2, 0, -0.11]}
      >
        <group position={[0, -0.13, -0.04]}>
          <group position={[0.02, 0.16, -0.01]}>
            <group position={[-0.07, -0.01, 0]}>
              <group position={[0.04, 0, 0]}>
                <group position={[0.02, -0.16, 0.01]}>
                  <group
                    position={[0, 0.13, 0.04]}
                    rotation={[-2.85, -0.06, 0]}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
      <group position={[-0.08, 0.55, 0.84]} rotation={[-1.55, 0, 0]} />
      <mesh
        geometry={nodes.Air_bangs.geometry}
        material={materials["Hair_Transparency.002_B107"]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Bra.geometry}
        material={materials.Bra_B113}
        scale={0.01}
      />
      <mesh
        geometry={nodes.CC_Base_Tongue.geometry}
        material={materials.Std_Tongue_B110}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Space_bun_L.geometry}
        material={materials.Hair_Transparency_B106}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Space_bun_R.geometry}
        material={materials["Hair_Transparency.001_B117"]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Underwear_Bottoms.geometry}
        material={materials.Underwear_Bottoms_B114}
        scale={0.01}
      />
    </group>
  );
}

// useGLTF.preload("/AstraFull-transformed.glb");
