/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Base({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Base-transformed.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Skin_1.geometry} material={materials.Stucco} />
      <mesh
        geometry={nodes.Skin_2.geometry}
        material={materials["Inner Nose"]}
      />
      <mesh
        geometry={nodes.Skin_3.geometry}
        material={materials["Nose Glow"]}
      />
      <mesh geometry={nodes.Skin_4.geometry} material={materials.Lips} />
      <group position={[0.07, 1.79, 0.07]} scale={0.06}>
        <mesh
          geometry={nodes.Sphere002.geometry}
          material={nodes.Sphere002.material}
        />
        <mesh
          geometry={nodes.Sphere002_1.geometry}
          material={nodes.Sphere002_1.material}
        />
      </group>
      <group position={[-0.07, 1.79, 0.07]} scale={0.06}>
        <mesh
          geometry={nodes.Sphere002.geometry}
          material={nodes.Sphere002.material}
        />
        <mesh
          geometry={nodes.Sphere002_1.geometry}
          material={nodes.Sphere002_1.material}
        />
      </group>
      <mesh geometry={nodes.Mag.geometry} material={materials.Ghost} />
      <mesh
        geometry={nodes.Armor_1.geometry}
        material={materials["Armor Plates"]}
      />
      <mesh
        geometry={nodes.Armor_2.geometry}
        material={materials["Armor Mech"]}
      />
    </group>
  );
}

// useGLTF.preload("/Base-transformed.glb");
