/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Confu({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/Confu.glb");
  const { actions } = useAnimations(animations, group);

  const color = "lightblue";

  useEffect(() => {
    console.log("This is BAYC MODEL ACTIONS", actions);
    setTimeout(() => {
      // actions["CC_Base|FBXExportClip_0"].setEffectiveWeight(0.2);
      // actions["CC_Base|FBXExportClip_0"].play();
    }, 0);
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="TestArmor" scale={0.01}>
          <primitive object={nodes.CC_Base_BoneRoot} />
          <group name="ATES_F_Suit_H" />
          <group name="Boxers" />
          <group name="CC_Base_Body" />
          <group name="CC_Base_Eye" />
          <group name="CC_Base_EyeOcclusion" />
          <group name="CC_Base_TearLine" />
          <group name="CC_Base_Teeth" />
          <group name="CC_Base_Tongue_1" />
          <group name="Chin_Curtain_Long_Full_1" />
          <group name="Chin_Curtain_Sparse_1" />
          <group name="Half_up" />
          <group name="Mustache_Horseshoe_1" />
          <group name="Old_Long" />
          <group name="Samurai_bun" />
          <group name="Stubble_Neck_1" />
          <group name="CC_Base_Body_1">
            <skinnedMesh
              name="CC_Base_Body_primitive0"
              geometry={nodes.CC_Base_Body_primitive0.geometry}
              material={materials.Std_Skin_Head}
              skeleton={nodes.CC_Base_Body_primitive0.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Body_primitive0.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Body_primitive0.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="CC_Base_Body_primitive1"
              geometry={nodes.CC_Base_Body_primitive1.geometry}
              material={materials.Std_Skin_Body}
              skeleton={nodes.CC_Base_Body_primitive1.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Body_primitive1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Body_primitive1.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="CC_Base_Body_primitive2"
              geometry={nodes.CC_Base_Body_primitive2.geometry}
              material={materials.Std_Skin_Arm}
              skeleton={nodes.CC_Base_Body_primitive2.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Body_primitive2.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Body_primitive2.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="CC_Base_Body_primitive3"
              geometry={nodes.CC_Base_Body_primitive3.geometry}
              material={materials.Std_Skin_Leg}
              skeleton={nodes.CC_Base_Body_primitive3.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Body_primitive3.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Body_primitive3.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="CC_Base_Body_primitive4"
              geometry={nodes.CC_Base_Body_primitive4.geometry}
              material={materials.Std_Nails}
              skeleton={nodes.CC_Base_Body_primitive4.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Body_primitive4.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Body_primitive4.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="CC_Base_Body_primitive5"
              geometry={nodes.CC_Base_Body_primitive5.geometry}
              material={materials.Std_Eyelash}
              skeleton={nodes.CC_Base_Body_primitive5.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Body_primitive5.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Body_primitive5.morphTargetInfluences
              }
            />
          </group>
          <group name="CC_Base_Eye_1">
            <skinnedMesh
              name="CC_Base_Eye_primitive0"
              geometry={nodes.CC_Base_Eye_primitive0.geometry}
              material={materials.Std_Eye_R}
              skeleton={nodes.CC_Base_Eye_primitive0.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Eye_primitive0.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Eye_primitive0.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="CC_Base_Eye_primitive1"
              geometry={nodes.CC_Base_Eye_primitive1.geometry}
              material={materials.Std_Cornea_R}
              skeleton={nodes.CC_Base_Eye_primitive1.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Eye_primitive1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Eye_primitive1.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="CC_Base_Eye_primitive2"
              geometry={nodes.CC_Base_Eye_primitive2.geometry}
              material={materials.Std_Eye_L}
              skeleton={nodes.CC_Base_Eye_primitive2.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Eye_primitive2.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Eye_primitive2.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="CC_Base_Eye_primitive3"
              geometry={nodes.CC_Base_Eye_primitive3.geometry}
              material={materials.Std_Cornea_L}
              skeleton={nodes.CC_Base_Eye_primitive3.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Eye_primitive3.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Eye_primitive3.morphTargetInfluences
              }
            />
          </group>
          <group name="CC_Base_EyeOcclusion_1">
            <skinnedMesh
              name="CC_Base_EyeOcclusion_primitive0"
              geometry={nodes.CC_Base_EyeOcclusion_primitive0.geometry}
              material={materials.Std_Eye_Occlusion_R}
              skeleton={nodes.CC_Base_EyeOcclusion_primitive0.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_EyeOcclusion_primitive0.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_EyeOcclusion_primitive0.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="CC_Base_EyeOcclusion_primitive1"
              geometry={nodes.CC_Base_EyeOcclusion_primitive1.geometry}
              material={materials.Std_Eye_Occlusion_L}
              skeleton={nodes.CC_Base_EyeOcclusion_primitive1.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_EyeOcclusion_primitive1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_EyeOcclusion_primitive1.morphTargetInfluences
              }
            />
          </group>
          <group name="CC_Base_TearLine_1">
            <skinnedMesh
              name="CC_Base_TearLine_primitive0"
              geometry={nodes.CC_Base_TearLine_primitive0.geometry}
              material={materials.Std_Tearline_R}
              skeleton={nodes.CC_Base_TearLine_primitive0.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_TearLine_primitive0.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_TearLine_primitive0.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="CC_Base_TearLine_primitive1"
              geometry={nodes.CC_Base_TearLine_primitive1.geometry}
              material={materials.Std_Tearline_L}
              skeleton={nodes.CC_Base_TearLine_primitive1.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_TearLine_primitive1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_TearLine_primitive1.morphTargetInfluences
              }
            />
          </group>
          <group name="CC_Base_Teeth_1">
            <skinnedMesh
              name="CC_Base_Teeth_primitive0"
              geometry={nodes.CC_Base_Teeth_primitive0.geometry}
              material={materials.Std_Upper_Teeth}
              skeleton={nodes.CC_Base_Teeth_primitive0.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Teeth_primitive0.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Teeth_primitive0.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="CC_Base_Teeth_primitive1"
              geometry={nodes.CC_Base_Teeth_primitive1.geometry}
              material={materials.Std_Lower_Teeth}
              skeleton={nodes.CC_Base_Teeth_primitive1.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Teeth_primitive1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Teeth_primitive1.morphTargetInfluences
              }
            />
          </group>
          <group name="Half_up_1">
            <skinnedMesh
              name="Half_up_primitive0"
              geometry={nodes.Half_up_primitive0.geometry}
              material={materials["Hair_Transparency.001"]}
              skeleton={nodes.Half_up_primitive0.skeleton}
            />
            <skinnedMesh
              name="Half_up_primitive1"
              geometry={nodes.Half_up_primitive1.geometry}
              material={materials.Scalp_Transparency}
              skeleton={nodes.Half_up_primitive1.skeleton}
            />
          </group>
          <group name="Old_Long_1">
            <skinnedMesh
              name="Old_Long_primitive0"
              geometry={nodes.Old_Long_primitive0.geometry}
              material={materials.Old_Long_Transparency}
              skeleton={nodes.Old_Long_primitive0.skeleton}
              morphTargetDictionary={
                nodes.Old_Long_primitive0.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.Old_Long_primitive0.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="Old_Long_primitive1"
              geometry={nodes.Old_Long_primitive1.geometry}
              material={materials.Old_Long_Base_Transparency}
              skeleton={nodes.Old_Long_primitive1.skeleton}
              morphTargetDictionary={
                nodes.Old_Long_primitive1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.Old_Long_primitive1.morphTargetInfluences
              }
            />
          </group>

          <skinnedMesh
            name="ATES_F_Suit_H_1"
            geometry={nodes.ATES_F_Suit_H_1.geometry}
            material={materials.ATES_F_Suit_H_Merge}
            material-color={color}
            skeleton={nodes.ATES_F_Suit_H_1.skeleton}
          />

          <skinnedMesh
            name="Boxers_1"
            geometry={nodes.Boxers_1.geometry}
            material={materials.Boxers}
            skeleton={nodes.Boxers_1.skeleton}
          />
          <skinnedMesh
            name="Samurai_bun_1"
            geometry={nodes.Samurai_bun_1.geometry}
            material={materials.Hair_Transparency}
            skeleton={nodes.Samurai_bun_1.skeleton}
          />
          <skinnedMesh
            name="Chin_Curtain_Sparse"
            geometry={nodes.Chin_Curtain_Sparse.geometry}
            material={materials.Beard_Transparency}
            skeleton={nodes.Chin_Curtain_Sparse.skeleton}
            morphTargetDictionary={
              nodes.Chin_Curtain_Sparse.morphTargetDictionary
            }
            morphTargetInfluences={
              nodes.Chin_Curtain_Sparse.morphTargetInfluences
            }
          />
          <skinnedMesh
            name="Stubble_Neck"
            geometry={nodes.Stubble_Neck.geometry}
            material={materials["Beard_Transparency.001"]}
            skeleton={nodes.Stubble_Neck.skeleton}
            morphTargetDictionary={nodes.Stubble_Neck.morphTargetDictionary}
            morphTargetInfluences={nodes.Stubble_Neck.morphTargetInfluences}
          />
          <skinnedMesh
            name="CC_Base_Tongue"
            geometry={nodes.CC_Base_Tongue.geometry}
            material={materials.Std_Tongue}
            skeleton={nodes.CC_Base_Tongue.skeleton}
            morphTargetDictionary={nodes.CC_Base_Tongue.morphTargetDictionary}
            morphTargetInfluences={nodes.CC_Base_Tongue.morphTargetInfluences}
          />
          <skinnedMesh
            name="Chin_Curtain_Long_Full"
            geometry={nodes.Chin_Curtain_Long_Full.geometry}
            material={materials["Beard_Transparency.003"]}
            skeleton={nodes.Chin_Curtain_Long_Full.skeleton}
            morphTargetDictionary={
              nodes.Chin_Curtain_Long_Full.morphTargetDictionary
            }
            morphTargetInfluences={
              nodes.Chin_Curtain_Long_Full.morphTargetInfluences
            }
          />
          <skinnedMesh
            name="Mustache_Horseshoe"
            geometry={nodes.Mustache_Horseshoe.geometry}
            material={materials["Beard_Transparency.002"]}
            skeleton={nodes.Mustache_Horseshoe.skeleton}
            morphTargetDictionary={
              nodes.Mustache_Horseshoe.morphTargetDictionary
            }
            morphTargetInfluences={
              nodes.Mustache_Horseshoe.morphTargetInfluences
            }
          />
        </group>
      </group>
    </group>
  );
}

// useGLTF.preload("/Confu.glb");
