/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Cow({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/cow.glb");
  const { actions } = useAnimations(animations, group);

  // useEffect(() => {
  //   setTimeout(() => {
  //     actions["Key|grp1|Action|grp1|Action"].play();
  //   }, 0);
  //   // console.log("This is COW ACTIONS", actions);
  //   // actions["metarig.001|metarigAction"].play();
  //   // actions["Armature|Armature|mixamo.com|Layer0"].play();
  // });
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        name="grp1"
        geometry={nodes.grp1.geometry}
        material={materials.Mat}
        morphTargetDictionary={nodes.grp1.morphTargetDictionary}
        morphTargetInfluences={nodes.grp1.morphTargetInfluences}
        scale={0.0014}
      />
    </group>
  );
}

// useGLTF.preload("/cow.glb");
