/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Animateria (https://sketchfab.com/Animateria)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cybercity-2099-v2-3b61335c2a004a9ea31c8dab59471222
title: CyberCity_2099_V2
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function CyberCity({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/CyberCity-transformed.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[33601.48, 10889.5, 25652.52]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={100}
          >
            <mesh
              geometry={nodes.Hovercars_Holograms_0.geometry}
              material={materials.Holograms}
            />
          </group>
          <group
            position={[-51323.47, 0, 339403.13]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={245360.69}
          >
            <mesh
              geometry={nodes.Streets_outline_Streets_outline_0.geometry}
              material={materials.Streets_outline}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Beacons_red_light_0.geometry}
              material={materials.red_light}
            />
            <mesh
              geometry={nodes.Beacons_beacons_base_0.geometry}
              material={materials.beacons_base}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Solar_panel_Solar_panel_0.geometry}
              material={materials.Solar_panel}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Solar_panel_base_Solar_panel_base_0.geometry}
              material={materials.Solar_panel_base}
            />
          </group>
          <group
            position={[6814.93, 5723.9, 8157.47]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={
                nodes.Publicity_neon_orange_Publicity_neon_orange_0.geometry
              }
              material={materials.Publicity_neon_orange}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Buildings_neon_Buildings_neon_0.geometry}
              material={materials.Buildings_neon}
            />
          </group>
          <group
            position={[-51323.47, 0, 339403.13]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={245360.69}
          >
            <mesh
              geometry={nodes.Buildings_1_top_Buildings_1_top_0.geometry}
              material={materials.Buildings_1_top}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Publicity_2D_Publicity_2D_0.geometry}
              material={materials.Publicity_2D}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Red_dish_Red_dish_0.geometry}
              material={materials.Red_dish}
            />
          </group>
          <group
            position={[-20305.06, 6960.81, 18946.49]}
            rotation={[-Math.PI / 2, 0, 2.36]}
            scale={100}
          >
            <mesh
              geometry={
                nodes.Publicity_neon_green_Publicity_neon_green_0.geometry
              }
              material={materials.Publicity_neon_green}
            />
          </group>
          <group
            position={[17582.67, 5337.33, 9320.89]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={
                nodes.Publicity_neon_pink_Publicity_neon_pink_0.geometry
              }
              material={materials.Publicity_neon_pink}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Publicity_lights_Publicity_lights_0.geometry}
              material={materials.Publicity_lights}
            />
            <mesh
              geometry={
                nodes.Publicity_lights_Publicity_lights_outline_0.geometry
              }
              material={materials.Publicity_lights_outline}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={
                nodes.Publicity_neon_blue_Publicity_neon_blue_0.geometry
              }
              material={materials.Publicity_neon_blue}
            />
          </group>
          <group
            position={[0, -76.99, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Trash_Trash_0.geometry}
              material={materials.Trash}
            />
          </group>
          <group
            position={[-1063.9, 0, -161.56]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[10638.3, 10638.3, 100]}
          >
            <mesh
              geometry={nodes.Terrain_Terrain_0.geometry}
              material={materials.Terrain}
            />
          </group>
          <group
            position={[-51323.47, 0, 339403.13]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={245360.69}
          >
            <mesh
              geometry={nodes.Buildings_1_Buildings_1_0.geometry}
              material={materials.Buildings_1}
            />
          </group>
          <group
            position={[-51323.47, 0, 339403.13]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={245360.69}
          >
            <mesh
              geometry={nodes.Buildings_0_Buildings_0_0.geometry}
              material={materials.Buildings_0}
            />
          </group>
          <group
            position={[-51323.47, 0, 339403.13]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={245360.69}
          >
            <mesh
              geometry={nodes.Bridge_outline_Bridge_outline_0.geometry}
              material={materials.Bridge_outline}
            />
          </group>
          <group
            position={[-51323.47, 0, 339403.13]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={245360.69}
          >
            <mesh
              geometry={nodes.Sidewalks_outline_Sidewalks_outline_0.geometry}
              material={materials.Sidewalks_outline}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Bridge_support_Bridge_support_0.geometry}
              material={materials.Bridge_support}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Buildings_adds_Buildings_adds_0.geometry}
              material={materials.Buildings_adds}
            />
          </group>
          <group
            position={[-51323.47, 0, 339403.13]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={245360.69}
          >
            <mesh
              geometry={nodes.Buildings_0_1_Buildings_0_1_0.geometry}
              material={materials.Buildings_0_1}
            />
          </group>
          <group
            position={[-51323.47, 0, 339403.13]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={245360.69}
          >
            <mesh
              geometry={nodes.Buildings_2_top_Buildings_2_top_0.geometry}
              material={materials.Buildings_2_top}
            />
          </group>
          <group
            position={[-1063.9, 0, -161.56]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[10638.3, 10638.3, 100]}
          >
            <mesh
              geometry={nodes.Terrain_base_Terrain_base_0.geometry}
              material={materials.Terrain_base}
            />
          </group>
          <group
            position={[-51323.47, 0, 339403.13]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={245360.69}
          >
            <mesh
              geometry={nodes.Buildings_0_top_Buildings_0_top_0.geometry}
              material={materials.Buildings_0_top}
            />
          </group>
          <group
            position={[-51323.47, 0, 339403.13]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={245360.69}
          >
            <mesh
              geometry={nodes.Sidewalks_Sidewalks_0.geometry}
              material={materials.Sidewalks}
            />
          </group>
          <group
            position={[-51323.47, 0, 339403.13]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={245360.69}
          >
            <mesh
              geometry={nodes.Streets_Streets_0.geometry}
              material={materials.Streets}
            />
          </group>
          <group
            position={[407.62, 21685.2, -100.55]}
            rotation={[2.27, 0.66, -2.58]}
            scale={100}
          >
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Streets_2_Streets_2_0.geometry}
              material={materials.Streets_2}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Hyper_loop_Hyper_loop_0.geometry}
              material={materials.Hyper_loop}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Buildings_adds_top_Buildings_adds_top_0.geometry}
              material={materials.Buildings_adds_top}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Buildings_Windows_Windows_no_emit_0.geometry}
              material={materials.Windows_no_emit}
            />
            <mesh
              geometry={nodes.Buildings_Windows_Windows_ilum_B_0.geometry}
              material={materials.Windows_ilum_B}
            />
            <mesh
              geometry={nodes.Buildings_Windows_Windows_ilum_Y_0.geometry}
              material={materials.Windows_ilum_Y}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Buildings_3_Buildings_3_0.geometry}
              material={materials.Buildings_3}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Publicity_neon_red_Publicity_neon_red_0.geometry}
              material={materials.Publicity_neon_red}
            />
          </group>
          <group
            position={[724.15, -31.94, 33491.97]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Trees_Base_Trees_Base_0.geometry}
              material={materials.Trees_Base}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Trees_Terrain_Trees_Base_0.geometry}
              material={materials.Trees_Base}
            />
            <mesh
              geometry={nodes.Trees_Terrain_Trees_Base_0_1.geometry}
              material={materials.Trees_Base}
            />
          </group>
          <group
            position={[-51323.47, 0, 339403.13]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={245360.69}
          >
            <mesh
              geometry={nodes.Buildings_2_Buildings_2_0.geometry}
              material={materials.Buildings_2}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Alpha_mesh_Alpha_mesh_0.geometry}
              material={materials.Alpha_mesh}
            />
          </group>
          <group position={[-8894.53, 1733.96, 1871.02]} scale={100}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-22157.92, 1733.96, -4822.07]} scale={100}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-6141.37, 1733.96, 10365.99]} scale={100}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[7969.4, 1733.96, 12797.61]} scale={100}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[2261.49, 1733.96, 16226.03]} scale={100}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Publicity_2D_1_Publicity_2D_0.geometry}
              material={materials.Publicity_2D}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Play_garden_Play_garden_0.geometry}
              material={materials.Play_garden}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Pool_Water_Pool_Water_0.geometry}
              material={materials.Pool_Water}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Publicity_lights_1_Publicity_lights_0.geometry}
              material={materials.Publicity_lights}
            />
            <mesh
              geometry={
                nodes.Publicity_lights_1_Publicity_lights_outline_0.geometry
              }
              material={materials.Publicity_lights_outline}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Lamp_Post_1_Lamp_Post_1_0.geometry}
              material={materials.Lamp_Post_1}
            />
            <mesh
              geometry={nodes.Lamp_Post_1_Blue_emit_0.geometry}
              material={materials.Blue_emit}
            />
          </group>
          <group
            position={[-51323.47, 0, 339403.13]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={245360.69}
          >
            <mesh
              geometry={nodes.Bridge_base_Bridge_base_0.geometry}
              material={materials.Bridge_base}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Lamp_post_lamppost_0.geometry}
              material={materials.lamppost}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

// useGLTF.preload("/CyberCity-transformed.glb");
