/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function DamagedHelmet({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/DamagedHelmet.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes["node_damagedHelmet_-6514"].geometry}
        material={materials.Material_MR}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

// useGLTF.preload("/DamagedHelmet.gltf");
