/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Double({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Double.glb");

  // Pull animation from this glb
  const { animations } = useGLTF("/FixedGrey-transformed.glb");
  const { actions } = useAnimations(animations, group);

  // console.log("This is ACTIONS GREY", actions);
  console.log("This is nodes double", nodes);

  useEffect(() => {
    // console.log("This is BAYC MODEL ACTIONS", actions);
    setTimeout(() => {
      // actions["CC_Base|FBXExportClip_0.001"].setEffectiveWeight(1);
      actions["CC_Base|FBXExportClip_0"].play();
    }, 0);
  });

  const color = "red";

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="Greytest" scale={1}>
          <primitive object={nodes.CC_Base_BoneRoot} />
          <group name="ATES_F_Suit_H" />
          <group name="CC_Base_Body" />
          <group name="CC_Base_EyeOcclusion" />
          <group name="CC_Base_Teeth" />
          <group name="CC_Base_Tongue_1" />
          <group name="CC_Game_Eye" />
          <group name="CC_Base_Body_1">
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Body_primitive0"
              geometry={nodes.CC_Base_Body_primitive0.geometry}
              material={materials.Std_Skin_Head}
              skeleton={nodes.CC_Base_Body_primitive0.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Body_primitive0.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Body_primitive0.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Body_primitive1"
              geometry={nodes.CC_Base_Body_primitive1.geometry}
              material={materials.Std_Skin_Body}
              skeleton={nodes.CC_Base_Body_primitive1.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Body_primitive1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Body_primitive1.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Body_primitive2"
              geometry={nodes.CC_Base_Body_primitive2.geometry}
              material={materials.Std_Skin_Arm}
              skeleton={nodes.CC_Base_Body_primitive2.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Body_primitive2.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Body_primitive2.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Body_primitive3"
              geometry={nodes.CC_Base_Body_primitive3.geometry}
              material={materials.Std_Skin_Leg}
              skeleton={nodes.CC_Base_Body_primitive3.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Body_primitive3.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Body_primitive3.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Body_primitive4"
              geometry={nodes.CC_Base_Body_primitive4.geometry}
              material={materials.Std_Nails}
              skeleton={nodes.CC_Base_Body_primitive4.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Body_primitive4.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Body_primitive4.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Body_primitive5"
              geometry={nodes.CC_Base_Body_primitive5.geometry}
              material={materials.Std_Eyelash}
              skeleton={nodes.CC_Base_Body_primitive5.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Body_primitive5.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Body_primitive5.morphTargetInfluences
              }
            />
          </group>
          <group name="CC_Base_EyeOcclusion_1">
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_EyeOcclusion_primitive0"
              geometry={nodes.CC_Base_EyeOcclusion_primitive0.geometry}
              material={materials.Std_Eye_Occlusion_R}
              skeleton={nodes.CC_Base_EyeOcclusion_primitive0.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_EyeOcclusion_primitive0.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_EyeOcclusion_primitive0.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_EyeOcclusion_primitive1"
              geometry={nodes.CC_Base_EyeOcclusion_primitive1.geometry}
              material={materials.Std_Eye_Occlusion_L}
              skeleton={nodes.CC_Base_EyeOcclusion_primitive1.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_EyeOcclusion_primitive1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_EyeOcclusion_primitive1.morphTargetInfluences
              }
            />
          </group>
          <group name="CC_Base_Teeth_1">
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Teeth_primitive0"
              geometry={nodes.CC_Base_Teeth_primitive0.geometry}
              material={materials.Std_Upper_Teeth}
              skeleton={nodes.CC_Base_Teeth_primitive0.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Teeth_primitive0.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Teeth_primitive0.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Teeth_primitive1"
              geometry={nodes.CC_Base_Teeth_primitive1.geometry}
              material={materials.Std_Lower_Teeth}
              skeleton={nodes.CC_Base_Teeth_primitive1.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Teeth_primitive1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Teeth_primitive1.morphTargetInfluences
              }
            />
          </group>
          <group name="CC_Game_Eye_1">
            <skinnedMesh
              frustumCulled={false}
              name="CC_Game_Eye_primitive0"
              geometry={nodes.CC_Game_Eye_primitive0.geometry}
              material={materials.Ga_Eye_R}
              skeleton={nodes.CC_Game_Eye_primitive0.skeleton}
              morphTargetDictionary={
                nodes.CC_Game_Eye_primitive0.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Game_Eye_primitive0.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Game_Eye_primitive1"
              geometry={nodes.CC_Game_Eye_primitive1.geometry}
              material={materials.Ga_Eye_L}
              skeleton={nodes.CC_Game_Eye_primitive1.skeleton}
              morphTargetDictionary={
                nodes.CC_Game_Eye_primitive1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Game_Eye_primitive1.morphTargetInfluences
              }
            />
          </group>

          <skinnedMesh
            frustumCulled={false}
            name="CC_Base_Tongue"
            geometry={nodes.CC_Base_Tongue.geometry}
            material={materials.Std_Tongue}
            skeleton={nodes.CC_Base_Tongue.skeleton}
            morphTargetDictionary={nodes.CC_Base_Tongue.morphTargetDictionary}
            morphTargetInfluences={nodes.CC_Base_Tongue.morphTargetInfluences}
          />

          <group name="ATES_F_Suit_H" />
          <skinnedMesh
            material-color={color}
            frustumCulled={false}
            name="ATES_F_Suit_H_1"
            geometry={nodes.ATES_F_Suit_H_1.geometry}
            material={materials.ATES_F_Suit_H_Merge}
            skeleton={nodes.ATES_F_Suit_H_1.skeleton}
          />

          <group name="E01_M_Suit_H" />
          <skinnedMesh
            material-color={color}
            frustumCulled={false}
            name="E01_M_Suit_H_1"
            geometry={nodes.E01_M_Suit_H_1.geometry}
            material={materials.E01_M_Suit_H_Merge}
            skeleton={nodes.ATES_F_Suit_H_1.skeleton}
          />
        </group>

        {/* {hidden === false ? (
                  <group name="GreyOppTest" position={[0, -0.02, 0]} scale={1}>
                  <primitive object={nodes.CC_Base_BoneRoot_1} />
                  <group name="E01_M_Suit_H" />
                  <skinnedMesh
                      frustumCulled={false}
                      name="E01_M_Suit_H_1"
                      geometry={nodes.E01_M_Suit_H_1.geometry}
                      material={materials.E01_M_Suit_H_Merge}
                      skeleton={nodes.E01_M_Suit_H_1.skeleton}
                  />
              </group>

): (<>
</>

)} */}
      </group>
    </group>
  );
}

// useGLTF.preload("/Double.glb");
