/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function FemaleGrey({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/FemaleGrey.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    // console.log("This is BAYC MODEL ACTIONS", actions);
    setTimeout(() => {
      actions["Export|A|Walk_M"].play();
    }, 0);
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="Export" scale={0.01}>
          <primitive object={nodes.CC_Base_BoneRoot} />
          <group name="Boots" />
          <group name="CC_Base_Body" />
          <group name="CC_Base_Eye" />
          <group name="CC_Base_EyeOcclusion" />
          <group name="CC_Base_TearLine" />
          <group name="CC_Base_Teeth" />
          <group name="CC_Base_Tongue_1" />
          <group name="Cyber_Legs" />
          <group name="Gloves" />
          <group name="Goggles_1" />
          <group name="Pants" />
          <group name="Protect" />
          <group name="T_Shirt_Cut" />
          <group name="CC_Base_Body_1">
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Body_primitive0"
              geometry={nodes.CC_Base_Body_primitive0.geometry}
              material={materials.Std_Skin_Head}
              skeleton={nodes.CC_Base_Body_primitive0.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Body_primitive0.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Body_primitive0.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Body_primitive1"
              geometry={nodes.CC_Base_Body_primitive1.geometry}
              material={materials.Std_Skin_Body}
              skeleton={nodes.CC_Base_Body_primitive1.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Body_primitive1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Body_primitive1.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Body_primitive2"
              geometry={nodes.CC_Base_Body_primitive2.geometry}
              material={materials.Std_Skin_Arm}
              skeleton={nodes.CC_Base_Body_primitive2.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Body_primitive2.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Body_primitive2.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Body_primitive3"
              geometry={nodes.CC_Base_Body_primitive3.geometry}
              material={materials.Std_Skin_Leg}
              skeleton={nodes.CC_Base_Body_primitive3.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Body_primitive3.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Body_primitive3.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Body_primitive4"
              geometry={nodes.CC_Base_Body_primitive4.geometry}
              material={materials.Std_Nails}
              skeleton={nodes.CC_Base_Body_primitive4.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Body_primitive4.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Body_primitive4.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Body_primitive5"
              geometry={nodes.CC_Base_Body_primitive5.geometry}
              material={materials.Std_Eyelash}
              skeleton={nodes.CC_Base_Body_primitive5.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Body_primitive5.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Body_primitive5.morphTargetInfluences
              }
            />
          </group>
          <group name="CC_Base_Eye_1">
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Eye_primitive0"
              geometry={nodes.CC_Base_Eye_primitive0.geometry}
              material={materials.Std_Eye_R}
              skeleton={nodes.CC_Base_Eye_primitive0.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Eye_primitive0.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Eye_primitive0.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Eye_primitive1"
              geometry={nodes.CC_Base_Eye_primitive1.geometry}
              material={materials.Std_Cornea_R}
              skeleton={nodes.CC_Base_Eye_primitive1.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Eye_primitive1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Eye_primitive1.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Eye_primitive2"
              geometry={nodes.CC_Base_Eye_primitive2.geometry}
              material={materials.Std_Eye_L}
              skeleton={nodes.CC_Base_Eye_primitive2.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Eye_primitive2.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Eye_primitive2.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Eye_primitive3"
              geometry={nodes.CC_Base_Eye_primitive3.geometry}
              material={materials.Std_Cornea_L}
              skeleton={nodes.CC_Base_Eye_primitive3.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Eye_primitive3.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Eye_primitive3.morphTargetInfluences
              }
            />
          </group>
          <group name="CC_Base_EyeOcclusion_1">
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_EyeOcclusion_primitive0"
              geometry={nodes.CC_Base_EyeOcclusion_primitive0.geometry}
              material={materials.Std_Eye_Occlusion_R}
              skeleton={nodes.CC_Base_EyeOcclusion_primitive0.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_EyeOcclusion_primitive0.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_EyeOcclusion_primitive0.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_EyeOcclusion_primitive1"
              geometry={nodes.CC_Base_EyeOcclusion_primitive1.geometry}
              material={materials.Std_Eye_Occlusion_L}
              skeleton={nodes.CC_Base_EyeOcclusion_primitive1.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_EyeOcclusion_primitive1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_EyeOcclusion_primitive1.morphTargetInfluences
              }
            />
          </group>
          <group name="CC_Base_TearLine_1">
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_TearLine_primitive0"
              geometry={nodes.CC_Base_TearLine_primitive0.geometry}
              material={materials.Std_Tearline_R}
              skeleton={nodes.CC_Base_TearLine_primitive0.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_TearLine_primitive0.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_TearLine_primitive0.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_TearLine_primitive1"
              geometry={nodes.CC_Base_TearLine_primitive1.geometry}
              material={materials.Std_Tearline_L}
              skeleton={nodes.CC_Base_TearLine_primitive1.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_TearLine_primitive1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_TearLine_primitive1.morphTargetInfluences
              }
            />
          </group>
          <group name="CC_Base_Teeth_1">
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Teeth_primitive0"
              geometry={nodes.CC_Base_Teeth_primitive0.geometry}
              material={materials.Std_Upper_Teeth}
              skeleton={nodes.CC_Base_Teeth_primitive0.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Teeth_primitive0.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Teeth_primitive0.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Teeth_primitive1"
              geometry={nodes.CC_Base_Teeth_primitive1.geometry}
              material={materials.Std_Lower_Teeth}
              skeleton={nodes.CC_Base_Teeth_primitive1.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Teeth_primitive1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Teeth_primitive1.morphTargetInfluences
              }
            />
          </group>
          <skinnedMesh
            frustumCulled={false}
            name="Boots_1"
            geometry={nodes.Boots_1.geometry}
            material={materials.Boots}
            skeleton={nodes.Boots_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            name="Cyber_Legs_1"
            geometry={nodes.Cyber_Legs_1.geometry}
            material={materials.Cyber_Legs}
            skeleton={nodes.Cyber_Legs_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            name="Gloves_1"
            geometry={nodes.Gloves_1.geometry}
            material={materials.Gloves}
            skeleton={nodes.Gloves_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            name="Goggles_2"
            geometry={nodes.Goggles_2.geometry}
            material={materials.Goggles}
            skeleton={nodes.Goggles_2.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            name="Pants_1"
            geometry={nodes.Pants_1.geometry}
            material={materials.Pants}
            skeleton={nodes.Pants_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            name="Protect_1"
            geometry={nodes.Protect_1.geometry}
            material={materials.Protect}
            skeleton={nodes.Protect_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            name="T_Shirt_Cut_1"
            geometry={nodes.T_Shirt_Cut_1.geometry}
            material={materials.T_Shirt_Cut}
            skeleton={nodes.T_Shirt_Cut_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            name="CC_Base_Tongue"
            geometry={nodes.CC_Base_Tongue.geometry}
            material={materials.Std_Tongue}
            skeleton={nodes.CC_Base_Tongue.skeleton}
            morphTargetDictionary={nodes.CC_Base_Tongue.morphTargetDictionary}
            morphTargetInfluences={nodes.CC_Base_Tongue.morphTargetInfluences}
          />
        </group>
      </group>
    </group>
  );
}

// useGLTF.preload("/FemaleGrey.glb");
