/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function FirstContact({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/FirstContact.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.sunsetMeshFrames_lambert1_0003.geometry}
        material={nodes.sunsetMeshFrames_lambert1_0003.material}
      />
      <mesh
        geometry={nodes.sunsetMeshFrames_lambert1_0004.geometry}
        material={nodes.sunsetMeshFrames_lambert1_0004.material}
      />
      <mesh
        geometry={nodes.sunsetMeshFrames_lambert1_0005.geometry}
        material={nodes.sunsetMeshFrames_lambert1_0005.material}
      />
      <mesh
        geometry={nodes.sunsetMeshFrames_lambert1_0006.geometry}
        material={nodes.sunsetMeshFrames_lambert1_0006.material}
      />
      <mesh
        geometry={nodes.sunsetMeshFrames_lambert1_0008.geometry}
        material={nodes.sunsetMeshFrames_lambert1_0008.material}
      />
      <mesh
        geometry={nodes.sunsetMeshFrames_lambert1_0007.geometry}
        material={materials["lambert1.001"]}
      />
    </group>
  );
}

// useGLTF.preload("/FirstContact.glb");
