/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Gallery2({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Gallery2.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[0, 0.13, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <mesh
          geometry={nodes.polySurface31.geometry}
          material={materials.lambert19}
        />
      </group>
      <mesh
        geometry={nodes.pTorus90.geometry}
        material={materials.lambert17}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.polySurface29.geometry}
        material={materials.lambert15}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.polySurface19.geometry}
        material={materials.lambert21}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.polySurface30.geometry}
        material={materials.lambert20}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  );
}

// useGLTF.preload("/Gallery2.glb");
