/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Hatchet({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/hatchet.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Box001.geometry}
        material={nodes.Box001.material}
        position={[0.59, 0.02, 0.01]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.03, 0.02, 0.03]}
      />
    </group>
  );
}

// useGLTF.preload("/hatchet.glb");
