/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Helmet({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/helmet.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes["300_helm"].geometry}
        material={materials.Helmet}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.Box001.geometry}
        material={materials.Hair}
        position={[0, 0.52, 0.09]}
        rotation={[0.07, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
    </group>
  );
}

// useGLTF.preload("/helmet.glb");
