/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useThree, useFrame, useTexture } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

export default function Kube(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/KubeNew-transformed.glb");

  // useFrame((state, delta) => {
  //   group.current.rotation.y = group.current.rotation.x += 0.01;
  // });

  useFrame(({ clock }) => {
    const a = clock.getElapsedTime();
    group.current.rotation.y = a / 8;
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0.89, 0]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[-0.39, -0.39, -0.39]}>
            <mesh
              geometry={nodes.ULF51_0.geometry}
              material={materials.SSS_BlackMarble}
            />
            <mesh
              geometry={nodes.PM3D_Cube3D1_8.geometry}
              material={materials.Glass02}
              position={[0, 0, -0.01]}
            />
            <mesh
              geometry={nodes.ULF49.geometry}
              material={materials.SSS_BlackMarble}
              position={[0, 0, 0]}
            />
            <mesh
              geometry={nodes.PM3D_Cube3D1_4.geometry}
              material={materials.Glass02}
              position={[-0.01, 0, 0.01]}
            />
            <mesh
              geometry={nodes.ULF46.geometry}
              material={materials.SSS_BlackMarble}
            />
            <mesh
              geometry={nodes.PM3D_Cube3D1_6.geometry}
              material={materials.Glass02}
              position={[0, 0, 0]}
            />
            <mesh
              geometry={nodes.ULF47.geometry}
              material={materials.SSS_BlackMarble}
            />
            <mesh
              geometry={nodes.PM3D_Cube3D1_7.geometry}
              material={materials.Glass02}
              position={[0, 0, 0]}
            />
            <mesh
              geometry={nodes.ULF41.geometry}
              material={materials.SSS_BlackMarble}
            />
            <mesh
              geometry={nodes.PM3D_Cube3D1_9.geometry}
              material={materials.Glass02}
              position={[0, 0, 0]}
            />
            <mesh
              geometry={nodes.ULF35.geometry}
              material={materials.SSS_BlackMarble}
            />
            <mesh
              geometry={nodes.PM3D_Cube3D1_5.geometry}
              material={materials.Glass02}
              position={[0.01, 0, 0.01]}
            />
            <mesh
              geometry={nodes.ULF32.geometry}
              material={materials.SSS_BlackMarble}
              position={[0, 0, 0.01]}
            />
            <mesh
              geometry={nodes.PM3D_Cube3D1_2.geometry}
              material={materials.Glass02}
              position={[-0.01, 0, 0]}
            />
            <mesh
              geometry={nodes.ULF29.geometry}
              material={materials.SSS_BlackMarble}
            />
            <mesh
              geometry={nodes.PM3D_Cube3D1_3.geometry}
              material={materials.Glass02}
              position={[0, -0.01, 0]}
            />
            <mesh
              geometry={nodes._6.geometry}
              material={materials.Gold_Raw_0_}
              position={[0.47, -0.59, -0.57]}
            />
            <mesh
              geometry={nodes._5.geometry}
              material={materials.Marble}
              position={[0.47, -0.59, -0.57]}
            />
            <mesh
              geometry={nodes._4.geometry}
              material={materials.Gold_Raw_0_}
              position={[0.47, -0.59, -0.57]}
            />
            <mesh
              geometry={nodes.PM3D_Cube3D1.geometry}
              material={materials.SSS_Emerald}
              position={[0.47, -0.59, -0.57]}
            />
            <mesh
              geometry={nodes._6_0.geometry}
              material={materials.Gold_Raw_0_}
              position={[1.36, 0.46, -0.57]}
              rotation={[0, 0, 1.58]}
            />
            <mesh
              geometry={nodes._5_0.geometry}
              material={materials.Marble}
              position={[1.36, 0.46, -0.57]}
              rotation={[0, 0, 1.58]}
            />
            <mesh
              geometry={nodes._4_0.geometry}
              material={materials.Gold_Raw_0_}
              position={[1.36, 0.46, -0.57]}
              rotation={[0, 0, 1.58]}
            />
            <mesh
              geometry={nodes.PM3D_Cube3D1_0.geometry}
              material={materials.SSS_Emerald}
              position={[1.36, 0.46, -0.57]}
              rotation={[0, 0, 1.58]}
            />
            <mesh
              geometry={nodes._6_1.geometry}
              material={materials.Gold_Raw_0_}
              position={[-0.57, -0.59, 0.32]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              geometry={nodes._5_1.geometry}
              material={materials.Marble}
              position={[-0.57, -0.59, 0.32]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              geometry={nodes._4_1.geometry}
              material={materials.Gold_Raw_0_}
              position={[-0.57, -0.59, 0.32]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              geometry={nodes.PM3D_Cube3D1_1.geometry}
              material={materials.SSS_Emerald}
              position={[-0.57, -0.59, 0.32]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              geometry={nodes._6_2.geometry}
              material={materials.Gold_Raw_0_}
              position={[0.32, -0.59, 1.35]}
              rotation={[-Math.PI, -0.01, -Math.PI]}
            />
            <mesh
              geometry={nodes._5_2.geometry}
              material={materials.Marble}
              position={[0.32, -0.59, 1.35]}
              rotation={[-Math.PI, -0.01, -Math.PI]}
            />
            <mesh
              geometry={nodes._4_2.geometry}
              material={materials.Gold_Raw_0_}
              position={[0.32, -0.59, 1.35]}
              rotation={[-Math.PI, -0.01, -Math.PI]}
            />
            <mesh
              geometry={nodes.PM3D_Cube3D1_10.geometry}
              material={materials.SSS_Emerald}
              position={[0.32, -0.59, 1.35]}
              rotation={[-Math.PI, -0.01, -Math.PI]}
            />
            <mesh
              geometry={nodes._6_3.geometry}
              material={materials.Gold_Raw_0_}
              position={[0.46, 1.35, -0.6]}
              rotation={[1.57, 0, 0]}
            />
            <mesh
              geometry={nodes._5_3.geometry}
              material={materials.Marble}
              position={[0.46, 1.35, -0.6]}
              rotation={[1.57, 0, 0]}
            />
            <mesh
              geometry={nodes._4_3.geometry}
              material={materials.Gold_Raw_0_}
              position={[0.46, 1.35, -0.6]}
              rotation={[1.57, 0, 0]}
            />
            <mesh
              geometry={nodes.PM3D_Cube3D1_11.geometry}
              material={materials.SSS_Emerald}
              position={[0.46, 1.35, -0.6]}
              rotation={[1.57, 0, 0]}
            />
            <mesh
              geometry={nodes._6_4.geometry}
              material={materials.Gold_Raw_0_}
              position={[0.46, 1.38, 1.34]}
              rotation={[3.14, 0, 0]}
            />
            <mesh
              geometry={nodes._5_4.geometry}
              material={materials.Marble}
              position={[0.46, 1.38, 1.34]}
              rotation={[3.14, 0, 0]}
            />
            <mesh
              geometry={nodes._4_4.geometry}
              material={materials.Gold_Raw_0_}
              position={[0.46, 1.38, 1.34]}
              rotation={[3.14, 0, 0]}
            />
            <mesh
              geometry={nodes.PM3D_Cube3D1_12.geometry}
              material={materials.SSS_Emerald}
              position={[0.46, 1.38, 1.34]}
              rotation={[3.14, 0, 0]}
            />
            <mesh
              geometry={nodes._6_5.geometry}
              material={materials.Gold_Raw_0_}
              position={[0.32, 1.36, -0.57]}
              rotation={[0, 0, 3.14]}
            />
            <mesh
              geometry={nodes._5_5.geometry}
              material={materials.Marble}
              position={[0.32, 1.36, -0.57]}
              rotation={[0, 0, 3.14]}
            />
            <mesh
              geometry={nodes._4_5.geometry}
              material={materials.Gold_Raw_0_}
              position={[0.32, 1.36, -0.57]}
              rotation={[0, 0, 3.14]}
            />
            <mesh
              geometry={nodes.PM3D_Cube3D1_13.geometry}
              material={materials.SSS_Emerald}
              position={[0.32, 1.36, -0.57]}
              rotation={[0, 0, 3.14]}
            />
            <mesh
              geometry={nodes._6_6.geometry}
              material={materials.Gold_Raw_0_}
              position={[1.34, 1.36, 0.32]}
              rotation={[-1.04, -1.56, 2.11]}
            />
            <mesh
              geometry={nodes._5_6.geometry}
              material={materials.Marble}
              position={[1.34, 1.36, 0.32]}
              rotation={[-1.04, -1.56, 2.11]}
            />
            <mesh
              geometry={nodes._4_6.geometry}
              material={materials.Gold_Raw_0_}
              position={[1.34, 1.36, 0.32]}
              rotation={[-1.04, -1.56, 2.11]}
            />
            <mesh
              geometry={nodes.PM3D_Cube3D1_14.geometry}
              material={materials.SSS_Emerald}
              position={[1.34, 1.36, 0.32]}
              rotation={[-1.04, -1.56, 2.11]}
            />
            <mesh
              geometry={nodes.Ball_000.geometry}
              material={materials.Glass02}
              position={[0.43, 0.41, 0.03]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

// useGLTF.preload('/KubeNew-transformed.glb')
