/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function ReptWeapon({
  eyecolor,
  color,
  armor,
  skin,
  head,
  weapon,
  animationClip,
  ...props
}) {
  const group = useRef();

  const { nodes, materials } = useGLTF(
    "/ReptMergeWeaponFixed3-transformed.glb"
  );

  const [dirPath, setDirPath] = useState("/ReptAnim2_Slash-transformed.glb");
  const [animationNumber, setAnimationNumber] = useState(
    "ReptAnim2_Motion_Motion_Anim_0"
  );

  useEffect(() => {
    //Logic for loading animations depending on character pose
    // if (weapon === "None") {
    //   setDirPath("/ReptAnim_Idle-transformed.glb");
    //   setAnimationNumber("ReptAnim1_Motion_Anim_0");
    // } else {
    //   setDirPath("/ReptAnim2_Slash-transformed.glb");
    //   setAnimationNumber("ReptAnim2_Motion_Motion_Anim_0");
    // }

    console.log("This is MODEL dirPath", dirPath);
    console.log("This is MODEL animations", animations);
    console.log("This is MODEL ACTIONS", actions);

    console.log("This is MODEL AC", animationClip);

    if (animationClip === "Play") {
      setTimeout(() => {
        console.log("1 clip");
        // actions["CC_Base|FBXExportClip_0.001"].setEffectiveWeight(1);

        if (actions[`${animationNumber}`]._effectiveTimeScale === 0) {
          actions[`${animationNumber}`].setEffectiveTimeScale(1);
        } else {
          actions[`${animationNumber}`].play();
        }
      }, 0);
    } else {
      setTimeout(() => {
        console.log("2 clip");
        // actions["CC_Base|FBXExportClip_0.001"].setEffectiveWeight(1);
        actions[`${animationNumber}`].setEffectiveTimeScale(0);
      }, 0);
    }

    setTimeout(() => {
      // actions["CC_Base|FBXExportClip_0.001"].setEffectiveWeight(1);
      actions[`${animationNumber}`].play();
    }, 0);
  }, [weapon, animationClip]);

  const { animations } = useGLTF(`${dirPath}`);
  const { actions } = useAnimations(animations, group);

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.root} />

      {armor === "None" ? (
        <>
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive0_1.geometry}
            material={materials.Std_Tongue}
            skeleton={nodes.node0_primitive0_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive1_1.geometry}
            material={materials.Std_Skin_Head}
            material-color={skin}
            skeleton={nodes.node0_primitive1_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive2_1.geometry}
            material={materials.Std_Skin_Body}
            material-color={skin}
            skeleton={nodes.node0_primitive2_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive3_1.geometry}
            material={materials.Std_Skin_Arm}
            material-color={skin}
            skeleton={nodes.node0_primitive3_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive4_1.geometry}
            material={materials.Std_Skin_Leg}
            material-color={skin}
            skeleton={nodes.node0_primitive4_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive5_1.geometry}
            material={materials.Std_Nails}
            material-color={skin}
            skeleton={nodes.node0_primitive5_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive6_1.geometry}
            material={materials.Std_Eyelash}
            skeleton={nodes.node0_primitive6_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive7_1.geometry}
            material={materials.Std_Tearline_R}
            skeleton={nodes.node0_primitive7_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive8_1.geometry}
            material={materials.Std_Tearline_R}
            skeleton={nodes.node0_primitive8_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive9_1.geometry}
            material={materials.Std_Tearline_R}
            skeleton={nodes.node0_primitive9_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive10_1.geometry}
            material={materials.Std_Tearline_R}
            skeleton={nodes.node0_primitive10_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive11_1.geometry}
            material={materials.Std_Upper_Teeth}
            skeleton={nodes.node0_primitive11_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive12_1.geometry}
            material={materials.Std_Lower_Teeth}
            skeleton={nodes.node0_primitive12_1.skeleton}
          />
        </>
      ) : (
        <></>
      )}

      {armor !== "None" ? (
        <>
          {/* HEAD ONLY */}
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive0_1.geometry}
            material={materials.Std_Tongue}
            skeleton={nodes.node0_primitive0_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive1_1.geometry}
            material={materials.Std_Skin_Head}
            material-color={skin}
            skeleton={nodes.node0_primitive1_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive6_1.geometry}
            material={materials.Std_Eyelash}
            skeleton={nodes.node0_primitive6_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive7_1.geometry}
            material={materials.Std_Tearline_R}
            skeleton={nodes.node0_primitive7_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive8_1.geometry}
            material={materials.Std_Tearline_R}
            skeleton={nodes.node0_primitive8_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive9_1.geometry}
            material={materials.Std_Tearline_R}
            skeleton={nodes.node0_primitive9_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive10_1.geometry}
            material={materials.Std_Tearline_R}
            skeleton={nodes.node0_primitive10_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive11_1.geometry}
            material={materials.Std_Upper_Teeth}
            skeleton={nodes.node0_primitive11_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive12_1.geometry}
            material={materials.Std_Lower_Teeth}
            skeleton={nodes.node0_primitive12_1.skeleton}
          />
        </>
      ) : (
        <></>
      )}

      {head !== "None" ? (
        <>
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive13_1.geometry}
            material={materials.PRCCM_SF2Helm}
            material-color={color}
            skeleton={nodes.node0_primitive13_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive14_1.geometry}
            material={materials.PRCCM_SF2Helm_Glass}
            material-color={color}
            skeleton={nodes.node0_primitive14_1.skeleton}
          />
        </>
      ) : (
        <></>
      )}

      {armor === "Beta" ? (
        <>
          {/* ARMOR 2 PRCCM*/}
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive15_1.geometry}
            material={materials.PRCCM_SF2Suit_Upper}
            material-color={color}
            skeleton={nodes.node0_primitive15_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive16_1.geometry}
            material={materials.PRCCM_SF2Suit_Lower}
            material-color={color}
            skeleton={nodes.node0_primitive16_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive17_1.geometry}
            material={materials.PRCCM_SF2Gloves}
            material-color={color}
            skeleton={nodes.node0_primitive17_1.skeleton}
          />
        </>
      ) : (
        <></>
      )}

      {armor === "Alpha" ? (
        <>
          {/* ARMOR */}
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive18_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive18_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive19_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive19_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive20_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive20_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive21_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive21_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive22_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive22_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive23_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive23_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive24_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive24_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive25_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive25_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive26_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive26_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive27_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive27_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive28_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive28_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive29_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive29_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive30_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive30_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive31_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive31_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive32_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive32_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive33_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive33_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive34_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive34_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive35_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive35_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive36_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive36_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive37_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive37_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive38_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive38_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive39_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive39_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive40_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive40_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive41_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive41_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive42_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive42_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive43_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive43_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive44_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive44_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive45_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive45_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive46_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive46_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive47_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive47_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive48_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive48_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive49_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive49_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive50_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive50_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive51_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive51_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive52_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive52_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive53_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive53_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive54_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive54_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive55_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive55_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive56_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive56_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive57_1.geometry}
            material={materials.Abs}
            material-color={color}
            skeleton={nodes.node0_primitive57_1.skeleton}
          />
        </>
      ) : (
        <></>
      )}

      <skinnedMesh
        frustumCulled={false}
        geometry={nodes.node0_primitive58_1.geometry}
        material={materials.Ga_Eye_R}
        material-color={eyecolor}
        skeleton={nodes.node0_primitive58_1.skeleton}
      />
      <skinnedMesh
        frustumCulled={false}
        geometry={nodes.node0_primitive59_1.geometry}
        material={materials.Ga_Eye_L}
        material-color={eyecolor}
        skeleton={nodes.node0_primitive59_1.skeleton}
      />

      {weapon !== "None" ? (
        <>
          {/* LASER SWORD */}
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive60_1.geometry}
            material={materials.GoZMesh_Default_Material}
            skeleton={nodes.node0_primitive60_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive61_1.geometry}
            material={materials.GoZMesh_Import_Material}
            skeleton={nodes.node0_primitive61_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive62_1.geometry}
            material={materials.GoZMesh_Import_Material_0}
            skeleton={nodes.node0_primitive62_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive63_1.geometry}
            material={materials.GoZMesh_Import_Material_1}
            skeleton={nodes.node0_primitive63_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive64_1.geometry}
            material={materials.GoZMesh_Default_Material_0}
            material-color={eyecolor}
            skeleton={nodes.node0_primitive64_1.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            geometry={nodes.node0_primitive65_1.geometry}
            material={materials.GoZMesh_Default_Material_0}
            material-color={eyecolor}
            skeleton={nodes.node0_primitive65_1.skeleton}
          />
        </>
      ) : (
        <></>
      )}
    </group>
  );
}

// useGLTF.preload("/ReptMergeWeaponFixed3-transformed.glb");
