/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function ReptFix({
  eyecolor,
  color,
  armor,
  skin,
  animationClip,
  ...props
}) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/ReptFix2.glb");

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.cc_base} />
      <skinnedMesh
        frustumCulled={false}
        geometry={nodes.node0_primitive0_1.geometry}
        material={materials.Std_Tongue}
        skeleton={nodes.node0_primitive0_1.skeleton}
      />
      <skinnedMesh
        frustumCulled={false}
        geometry={nodes.node0_primitive1_1.geometry}
        material={materials.Std_Skin_Head}
        material-color={skin}
        skeleton={nodes.node0_primitive1_1.skeleton}
      />
      <skinnedMesh
        frustumCulled={false}
        geometry={nodes.node0_primitive2_1.geometry}
        material={materials.Std_Skin_Body}
        material-color={skin}
        skeleton={nodes.node0_primitive2_1.skeleton}
      />
      <skinnedMesh
        frustumCulled={false}
        geometry={nodes.node0_primitive3_1.geometry}
        material={materials.Std_Skin_Arm}
        material-color={skin}
        skeleton={nodes.node0_primitive3_1.skeleton}
      />
      <skinnedMesh
        frustumCulled={false}
        geometry={nodes.node0_primitive4_1.geometry}
        material={materials.Std_Skin_Leg}
        material-color={skin}
        skeleton={nodes.node0_primitive4_1.skeleton}
      />
      <skinnedMesh
        frustumCulled={false}
        geometry={nodes.node0_primitive5_1.geometry}
        material={materials.Std_Nails}
        skeleton={nodes.node0_primitive5_1.skeleton}
      />
      <skinnedMesh
        frustumCulled={false}
        geometry={nodes.node0_primitive6_1.geometry}
        material={materials.Std_Eyelash}
        skeleton={nodes.node0_primitive6_1.skeleton}
      />
      <skinnedMesh
        frustumCulled={false}
        geometry={nodes.node0_primitive7_1.geometry}
        material={materials.Std_Upper_Teeth}
        skeleton={nodes.node0_primitive7_1.skeleton}
      />
      <skinnedMesh
        frustumCulled={false}
        geometry={nodes.node0_primitive8_1.geometry}
        material={materials.Std_Lower_Teeth}
        skeleton={nodes.node0_primitive8_1.skeleton}
      />
      <skinnedMesh
        frustumCulled={false}
        geometry={nodes.node0_primitive9_1.geometry}
        material={materials.Std_Eye_Occlusion_R}
        skeleton={nodes.node0_primitive9_1.skeleton}
      />
      <skinnedMesh
        frustumCulled={false}
        geometry={nodes.node0_primitive10_1.geometry}
        material={materials.Std_Eye_Occlusion_L}
        skeleton={nodes.node0_primitive10_1.skeleton}
      />
      <skinnedMesh
        frustumCulled={false}
        geometry={nodes.node0_primitive11_1.geometry}
        material={materials.PRCCM_SF2Suit_Upper}
        material-color={color}
        skeleton={nodes.node0_primitive11_1.skeleton}
      />
      <skinnedMesh
        frustumCulled={false}
        geometry={nodes.node0_primitive12_1.geometry}
        material={materials.PRCCM_SF2Suit_Lower}
        material-color={color}
        skeleton={nodes.node0_primitive12_1.skeleton}
      />
      <skinnedMesh
        frustumCulled={false}
        geometry={nodes.node0_primitive13_1.geometry}
        material={materials.PRCCM_SF2Gloves}
        material-color={color}
        skeleton={nodes.node0_primitive13_1.skeleton}
      />
      <skinnedMesh
        frustumCulled={false}
        geometry={nodes.node0_primitive14_1.geometry}
        material={materials.Ga_Eye_R}
        material-color={eyecolor}
        skeleton={nodes.node0_primitive14_1.skeleton}
      />
      <skinnedMesh
        frustumCulled={false}
        geometry={nodes.node0_primitive15_1.geometry}
        material={materials.Ga_Eye_L}
        material-color={eyecolor}
        skeleton={nodes.node0_primitive15_1.skeleton}
      />
    </group>
  );
}

// useGLTF.preload("/ReptFix2.glb");
