/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations, useTexture } from "@react-three/drei";
import * as THREE from "three";

export default function RepV1({
  eyecolor,
  color,
  armor,
  animationClip,
  ...props
}) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/RepV1-transformed.glb");

  const { animations } = useGLTF("/WaveRep.glb");
  const { actions } = useAnimations(animations, group);

  const texture1 = useTexture(
    "https://i.postimg.cc/jjMhD6rC/PRCCM-SF2-Suit-Upper-Diffuse.png"
  );

  const newMat = new THREE.MeshBasicMaterial({
    normalMap: materials.__meshes_Merge,
  });

  console.log("This is material mesh", materials.__meshes_Merge);
  useEffect(() => {
    // console.log("This is BAYC MODEL ACTIONS", actions);
    // console.log("This is BAYC MODEL AC", animationClip);
    if (animationClip === "1") {
      setTimeout(() => {
        // console.log("1 clip");
        // actions["CC_Base|FBXExportClip_0.001"].setEffectiveWeight(1);

        if (actions["CC_Base|FBXExportClip_0"]._effectiveTimeScale === 0) {
          actions["CC_Base|FBXExportClip_0"].setEffectiveTimeScale(1);
        } else {
          actions["CC_Base|FBXExportClip_0"].play();
        }
      }, 0);
    } else {
      setTimeout(() => {
        // console.log("2 clip");
        // actions["CC_Base|FBXExportClip_0.001"].setEffectiveWeight(1);
        actions["CC_Base|FBXExportClip_0"].setEffectiveTimeScale(0);
      }, 0);
    }

    // setTimeout(() => {
    //     // actions["CC_Base|FBXExportClip_0.001"].setEffectiveWeight(1);
    //     actions["CC_Base|FBXExportClip_0"].play();
    // }, 0);
  }, [animationClip]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="ReptilianV2_Cloth_AETS_BaseBW001" scale={1.6}>
          <primitive object={nodes.CC_Base_BoneRoot} />
          <group name="ATES_M_Suit_H" />
          <group name="CC_Base_Body" />
          <group name="CC_Base_EyeOcclusion" />
          <group name="CC_Base_Teeth" />
          <group name="CC_Base_Tongue_1" />
          <group name="CC_Game_Eye" />
          <group name="PRCCM_SF2Gloves" />
          <group name="PRCCM_SF2Suit" />
          <group name="CC_Base_Body_1">
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Body_primitive0"
              geometry={nodes.CC_Base_Body_primitive0.geometry}
              material={materials.Std_Skin_Head}
              skeleton={nodes.CC_Base_Body_primitive0.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Body_primitive0.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Body_primitive0.morphTargetInfluences
              }
            />

            {armor === "None" ? (
              <>
                <skinnedMesh
                  frustumCulled={false}
                  name="CC_Base_Body_primitive1"
                  geometry={nodes.CC_Base_Body_primitive1.geometry}
                  material={materials.Std_Skin_Body}
                  skeleton={nodes.CC_Base_Body_primitive1.skeleton}
                  morphTargetDictionary={
                    nodes.CC_Base_Body_primitive1.morphTargetDictionary
                  }
                  morphTargetInfluences={
                    nodes.CC_Base_Body_primitive1.morphTargetInfluences
                  }
                />
                <skinnedMesh
                  frustumCulled={false}
                  name="CC_Base_Body_primitive2"
                  geometry={nodes.CC_Base_Body_primitive2.geometry}
                  material={materials.Std_Skin_Arm}
                  skeleton={nodes.CC_Base_Body_primitive2.skeleton}
                  morphTargetDictionary={
                    nodes.CC_Base_Body_primitive2.morphTargetDictionary
                  }
                  morphTargetInfluences={
                    nodes.CC_Base_Body_primitive2.morphTargetInfluences
                  }
                />
                <skinnedMesh
                  frustumCulled={false}
                  name="CC_Base_Body_primitive3"
                  geometry={nodes.CC_Base_Body_primitive3.geometry}
                  material={materials.Std_Skin_Leg}
                  skeleton={nodes.CC_Base_Body_primitive3.skeleton}
                  morphTargetDictionary={
                    nodes.CC_Base_Body_primitive3.morphTargetDictionary
                  }
                  morphTargetInfluences={
                    nodes.CC_Base_Body_primitive3.morphTargetInfluences
                  }
                />
                <skinnedMesh
                  frustumCulled={false}
                  name="CC_Base_Body_primitive4"
                  geometry={nodes.CC_Base_Body_primitive4.geometry}
                  material={materials.Std_Nails}
                  skeleton={nodes.CC_Base_Body_primitive4.skeleton}
                  morphTargetDictionary={
                    nodes.CC_Base_Body_primitive4.morphTargetDictionary
                  }
                  morphTargetInfluences={
                    nodes.CC_Base_Body_primitive4.morphTargetInfluences
                  }
                />
                <skinnedMesh
                  frustumCulled={false}
                  name="CC_Base_Body_primitive5"
                  geometry={nodes.CC_Base_Body_primitive5.geometry}
                  material={materials.Std_Eyelash}
                  skeleton={nodes.CC_Base_Body_primitive5.skeleton}
                  morphTargetDictionary={
                    nodes.CC_Base_Body_primitive5.morphTargetDictionary
                  }
                  morphTargetInfluences={
                    nodes.CC_Base_Body_primitive5.morphTargetInfluences
                  }
                />
              </>
            ) : (
              <></>
            )}
          </group>
          <group name="CC_Base_EyeOcclusion_1">
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_EyeOcclusion_primitive0"
              geometry={nodes.CC_Base_EyeOcclusion_primitive0.geometry}
              material={materials.Std_Eye_Occlusion_R}
              skeleton={nodes.CC_Base_EyeOcclusion_primitive0.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_EyeOcclusion_primitive0.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_EyeOcclusion_primitive0.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_EyeOcclusion_primitive1"
              geometry={nodes.CC_Base_EyeOcclusion_primitive1.geometry}
              material={materials.Std_Eye_Occlusion_L}
              skeleton={nodes.CC_Base_EyeOcclusion_primitive1.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_EyeOcclusion_primitive1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_EyeOcclusion_primitive1.morphTargetInfluences
              }
            />
          </group>
          <group name="CC_Base_Teeth_1">
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Teeth_primitive0"
              geometry={nodes.CC_Base_Teeth_primitive0.geometry}
              material={materials.Std_Upper_Teeth}
              skeleton={nodes.CC_Base_Teeth_primitive0.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Teeth_primitive0.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Teeth_primitive0.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Teeth_primitive1"
              geometry={nodes.CC_Base_Teeth_primitive1.geometry}
              material={materials.Std_Lower_Teeth}
              skeleton={nodes.CC_Base_Teeth_primitive1.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Teeth_primitive1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Teeth_primitive1.morphTargetInfluences
              }
            />
          </group>
          <group name="CC_Game_Eye_1">
            <skinnedMesh
              frustumCulled={false}
              name="CC_Game_Eye_primitive0"
              geometry={nodes.CC_Game_Eye_primitive0.geometry}
              material={materials.Ga_Eye_R}
              material-color={eyecolor}
              skeleton={nodes.CC_Game_Eye_primitive0.skeleton}
              morphTargetDictionary={
                nodes.CC_Game_Eye_primitive0.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Game_Eye_primitive0.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Game_Eye_primitive1"
              geometry={nodes.CC_Game_Eye_primitive1.geometry}
              material={materials.Ga_Eye_L}
              material-color={eyecolor}
              skeleton={nodes.CC_Game_Eye_primitive1.skeleton}
              morphTargetDictionary={
                nodes.CC_Game_Eye_primitive1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Game_Eye_primitive1.morphTargetInfluences
              }
            />
          </group>

          {armor === "Alpha" ? (
            <skinnedMesh
              frustumCulled={false}
              name="ATES_M_Suit_H_1"
              geometry={nodes.ATES_M_Suit_H_1.geometry}
              material={materials.ATES_M_Suit_H_Merge}
              material-color={color}
              skeleton={nodes.ATES_M_Suit_H_1.skeleton}
            />
          ) : (
            <></>
          )}

          {armor === "Beta" ? (
            <>
              {" "}
              <skinnedMesh
                frustumCulled={false}
                name="PRCCM_SF2Gloves_1"
                geometry={nodes.PRCCM_SF2Gloves_1.geometry}
                material={materials.__meshes_Merge}
                material-color={color}
                skeleton={nodes.PRCCM_SF2Gloves_1.skeleton}
              />
              <skinnedMesh
                frustumCulled={false}
                name="PRCCM_SF2Suit_1"
                geometry={nodes.PRCCM_SF2Suit_1.geometry}
                material={materials.__meshes_Merge}
                // material-normalMap={newMat}
                material-color={color}
                skeleton={nodes.PRCCM_SF2Suit_1.skeleton}
              />
            </>
          ) : (
            <></>
          )}

          <skinnedMesh
            frustumCulled={false}
            name="CC_Base_Tongue"
            geometry={nodes.CC_Base_Tongue.geometry}
            material={materials.Std_Tongue}
            skeleton={nodes.CC_Base_Tongue.skeleton}
            morphTargetDictionary={nodes.CC_Base_Tongue.morphTargetDictionary}
            morphTargetInfluences={nodes.CC_Base_Tongue.morphTargetInfluences}
          />
        </group>
        <group name="ReptilianV2_Cloth_AETS_BaseBW" scale={1.6}>
          <group name="Shadow_Catcher" rotation={[-Math.PI / 2, 0, 0]}>
            <group name="CC_Base_Pivot" position={[0, 0, -1.53]}>
              <group name="Plane_001" position={[0, 0, 1.59]} />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

// useGLTF.preload("/RepV1-transformed.glb");
