/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Thor({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Thor-transformed.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.CC_Base_Body_primitive0.geometry}
          material={materials.Std_Skin_Head_1_B100}
        />
        <mesh
          geometry={nodes.CC_Base_Body_primitive1.geometry}
          material={materials.Std_Skin_Body_1_B101}
        />
        <mesh
          geometry={nodes.CC_Base_Body_primitive2.geometry}
          material={materials.Std_Skin_Arm_1_B102}
        />
        <mesh
          geometry={nodes.CC_Base_Body_primitive3.geometry}
          material={materials.Std_Skin_Leg_1_B103}
        />
        <mesh
          geometry={nodes.CC_Base_Body_primitive4.geometry}
          material={materials.Std_Nails_1_B104}
        />
        <mesh
          geometry={nodes.CC_Base_Body_primitive5.geometry}
          material={materials.Std_Eyelash_1_B105}
        />
      </group>
      <group scale={0.01}>
        <mesh
          geometry={nodes.CC_Base_EyeOcclusion_primitive0.geometry}
          material={materials.Std_Eye_Occlusion_R_1}
        />
        <mesh
          geometry={nodes.CC_Base_EyeOcclusion_primitive1.geometry}
          material={materials.Std_Eye_Occlusion_L_1}
        />
      </group>
      <group scale={0.01}>
        <mesh
          geometry={nodes.CC_Base_TearLine_primitive0.geometry}
          material={materials.Std_Tearline_R_1}
        />
        <mesh
          geometry={nodes.CC_Base_TearLine_primitive1.geometry}
          material={materials.Std_Tearline_L_1}
        />
      </group>
      <group scale={0.01}>
        <mesh
          geometry={nodes.CC_Base_Teeth_primitive0.geometry}
          material={materials.Std_Upper_Teeth_1_B121}
        />
        <mesh
          geometry={nodes.CC_Base_Teeth_primitive1.geometry}
          material={materials.Std_Lower_Teeth_1_B122}
        />
      </group>
      <group scale={0.01}>
        <mesh
          geometry={nodes.Custom_Eye_primitive0.geometry}
          material={materials.__Cornea_1_B111}
        />
        <mesh
          geometry={nodes.Custom_Eye_primitive1.geometry}
          material={materials.__Eyes_1_B112}
        />
        <mesh
          geometry={nodes.Custom_Eye_primitive2.geometry}
          material={materials.__Iris_1_B113}
        />
        <mesh
          geometry={nodes.Custom_Eye_primitive3.geometry}
          material={materials.__Pupil_1_B114}
        />
      </group>
      <group scale={0.01}>
        <mesh
          geometry={nodes.Female_Angled_primitive0.geometry}
          material={materials.Female_Angled_Transparency_1_B118}
        />
        <mesh
          geometry={nodes.Female_Angled_primitive1.geometry}
          material={materials.Female_Angled_Base_Transparency_1_B119}
        />
      </group>
      <group scale={0.01}>
        <mesh
          geometry={nodes.Hair_primitive0.geometry}
          material={materials.scalp_long_straight_Transparency_1_B116}
        />
        <mesh
          geometry={nodes.Hair_primitive1.geometry}
          material={materials.long_straight_Transparency_1_B117}
        />
      </group>
      <group scale={0.01}>
        <mesh
          geometry={nodes.HG_Body_003_primitive0.geometry}
          material={materials.Tech_2_1_B106}
        />
        <mesh
          geometry={nodes.HG_Body_003_primitive1.geometry}
          material={materials.Armor_Plates_1_B107}
        />
        <mesh
          geometry={nodes.HG_Body_003_primitive2.geometry}
          material={materials.Under_Plates_1_B108}
        />
        <mesh
          geometry={nodes.HG_Body_003_primitive3.geometry}
          material={materials.Copper_1_B109}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0.02, 1.6]} rotation={[0, 0, -Math.PI]}>
          <group position={[0, 0.28, 0.08]} rotation={[-1.57, 0, 3.14]} />
        </group>
        <group position={[0, 0, 1]} rotation={[1.7, 0, 0]}>
          <group position={[0, 0.08, 0]} rotation={[0.09, 0, 0]}>
            <group position={[0, 0.04, 0]} rotation={[-0.37, 0, 0]}>
              <group position={[0, 0.14, 0]} rotation={[-0.01, 0, 0]}>
                <group position={[0, 0.27, 0]} rotation={[0.42, 0, 0]}>
                  <group position={[0, 0.03, 0]} rotation={[-0.08, 0, 0]} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
      <group position={[0, 1.04, 0.01]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, -0.02, 0.08]}>
          <group rotation={[1.79, 0, 0]}>
            <group position={[0, -0.04, 0]} rotation={[-1.79, 0, 0]}>
              <group rotation={[1.7, 0, 0]}>
                <group position={[0, -0.08, 0]}>
                  <group rotation={[0, -1.08, 0]} />
                  <group
                    position={[0.1, -0.02, -0.01]}
                    rotation={[3.03, 0, 0.02]}
                  >
                    <group position={[0, 0.48, 0]} rotation={[0.02, 0, -0.01]}>
                      <group
                        position={[0, 0.47, 0]}
                        rotation={[-1.33, 0.05, -0.11]}
                      />
                      <group position={[0, 0.24, 0]} rotation={[0, -0.02, 0]} />
                    </group>
                    <group position={[0, 0.24, 0]} />
                  </group>
                  <group
                    position={[-0.1, -0.02, -0.01]}
                    rotation={[3.03, 0, -0.02]}
                  >
                    <group position={[0, 0.48, 0]} rotation={[0.02, 0, 0.01]}>
                      <group
                        position={[0, 0.47, 0]}
                        rotation={[-1.33, -0.05, 0.11]}
                      />
                      <group position={[0, 0.24, 0]} rotation={[0, 0.02, 0]} />
                    </group>
                    <group position={[0, 0.24, 0]} />
                  </group>
                  <group position={[0.1, -0.02, -0.01]} rotation={[-1.7, 0, 0]}>
                    <group rotation={[-1.55, 0, 0.02]}>
                      <group
                        position={[0, 0.48, 0]}
                        rotation={[0.02, 0, -0.01]}
                      >
                        <group
                          position={[0, 0.47, 0]}
                          rotation={[-1.33, 0.05, -0.11]}
                        >
                          <group
                            position={[0, 0.15, 0]}
                            rotation={[2.81, 0.06, 3.1]}
                          />
                        </group>
                      </group>
                    </group>
                    <group rotation={[-1.55, 0.01, 0.02]}>
                      <group rotation={[-0.01, 0, 0]} />
                    </group>
                  </group>
                  <group
                    position={[0.1, -0.02, -0.01]}
                    rotation={[3.03, 0, 0.02]}
                  />
                  <group
                    position={[0.1, -0.02, -0.01]}
                    rotation={[3.03, 0, 0.02]}
                  >
                    <group position={[0, 0.24, 0]}>
                      <group
                        position={[0, 0.24, 0]}
                        rotation={[0.02, 0, -0.01]}
                      >
                        <group position={[0, 0.24, 0]}>
                          <group
                            position={[0, 0.24, 0]}
                            rotation={[-1.33, 0.05, -0.11]}
                          >
                            <group
                              position={[0, 0.15, 0]}
                              rotation={[2.81, 0.06, 3.1]}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group
                    position={[-0.1, -0.02, -0.01]}
                    rotation={[-1.7, 0, 0]}
                  >
                    <group rotation={[-1.55, 0, -0.02]}>
                      <group position={[0, 0.48, 0]} rotation={[0.02, 0, 0.01]}>
                        <group
                          position={[0, 0.47, 0]}
                          rotation={[-1.33, -0.05, 0.11]}
                        >
                          <group
                            position={[0, 0.15, 0]}
                            rotation={[2.81, -0.06, -3.1]}
                          />
                        </group>
                      </group>
                    </group>
                    <group rotation={[-1.55, -0.01, -0.02]}>
                      <group rotation={[-0.01, 0, 0]} />
                    </group>
                  </group>
                  <group
                    position={[-0.1, -0.02, -0.01]}
                    rotation={[3.03, 0, -0.02]}
                  />
                  <group
                    position={[-0.1, -0.02, -0.01]}
                    rotation={[3.03, 0, -0.02]}
                  >
                    <group position={[0, 0.24, 0]}>
                      <group position={[0, 0.24, 0]} rotation={[0.02, 0, 0.01]}>
                        <group position={[0, 0.24, 0]}>
                          <group
                            position={[0, 0.24, 0]}
                            rotation={[-1.33, -0.05, 0.11]}
                          >
                            <group
                              position={[0, 0.15, 0]}
                              rotation={[2.81, -0.06, -3.1]}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group rotation={[0.09, 0, 0]} />
              </group>
            </group>
          </group>
        </group>
        <group position={[0, -0.02, 0.08]}>
          <group rotation={[1.43, 0, 0]}>
            <group rotation={[0.37, 0, 0]}>
              <group rotation={[-0.37, 0, 0]} />
            </group>
            <group position={[0, 0.14, 0]} rotation={[-1.43, 0, 0]}>
              <group rotation={[1.42, 0, 0]}>
                <group position={[0, 0.27, 0]} rotation={[0.42, 0, 0]}>
                  <group position={[0, 0.03, 0]} rotation={[-0.08, 0, 0]}>
                    <group position={[0, 0.04, 0]} rotation={[-0.19, 0, 0]}>
                      <group rotation={[-1.57, 0, -Math.PI]}>
                        <group
                          position={[0, 0.1, 0.03]}
                          rotation={[0, 0, Math.PI]}
                        />
                        <group
                          position={[0, 0.1, 0.01]}
                          rotation={[0, 0, Math.PI]}
                        />
                        <group
                          position={[-0.03, 0.07, 0.08]}
                          rotation={[3.14, 0.2, -3.14]}
                        >
                          <group
                            position={[0.02, 0.01, -0.01]}
                            rotation={[-1.44, -0.58, 0.24]}
                          />
                          <group
                            position={[0.01, 0.02, -0.01]}
                            rotation={[-1.49, -0.39, 0.22]}
                          />
                          <group
                            position={[0, 0.02, -0.01]}
                            rotation={[-1.55, -0.11, 0.2]}
                          />
                          <group
                            position={[-0.01, 0.02, 0]}
                            rotation={[-1.56, -0.06, 0.2]}
                          />
                          <group
                            position={[-0.02, 0.02, 0.01]}
                            rotation={[-1.54, -0.16, 0.2]}
                          />
                          <group
                            position={[-0.01, 0.02, 0.01]}
                            rotation={[-1.56, -0.05, 0.2]}
                          />
                          <group
                            position={[0.01, 0.02, 0.01]}
                            rotation={[-1.55, -0.11, 0.2]}
                          />
                          <group
                            position={[0.01, 0.01, 0]}
                            rotation={[-1.54, -0.14, 0.2]}
                          />
                          <group
                            position={[0.02, 0.01, -0.01]}
                            rotation={[-1.48, -0.44, 0.22]}
                          />
                          <group
                            position={[0.01, 0.02, -0.01]}
                            rotation={[-1.54, -0.16, 0.2]}
                          />
                          <group
                            position={[0, 0.02, -0.01]}
                            rotation={[-1.53, -0.22, 0.21]}
                          />
                          <group
                            position={[-0.01, 0.02, 0]}
                            rotation={[-1.56, -0.06, 0.2]}
                          />
                          <group rotation={[0, 0, 0.02]} />
                          <group rotation={[2.82, -0.73, 2.12]} />
                          <group rotation={[1.06, -1.18, 0.7]} />
                          <group rotation={[1.6, 1.27, -1.34]} />
                          <group rotation={[3.01, 0.13, -2.38]} />
                          <group rotation={[-2.9, -0.54, -1.97]} />
                          <group rotation={[-1.65, -1.24, -1.23]} />
                          <group rotation={[-0.33, 0.37, 0.11]} />
                          <group rotation={[-3.07, 0.05, 2.58]} />
                        </group>
                        <group
                          position={[0.03, 0.07, 0.08]}
                          rotation={[3.14, -0.2, 3.14]}
                        >
                          <group
                            position={[-0.02, 0.01, -0.01]}
                            rotation={[-1.47, 0.45, -0.22]}
                          />
                          <group
                            position={[-0.01, 0.02, -0.01]}
                            rotation={[-1.5, 0.34, -0.21]}
                          />
                          <group
                            position={[0, 0.03, -0.01]}
                            rotation={[-1.55, 0.13, -0.2]}
                          />
                          <group
                            position={[0.01, 0.02, 0]}
                            rotation={[-1.56, 0.07, -0.2]}
                          />
                          <group
                            position={[0.01, 0.02, 0.01]}
                            rotation={[-1.55, 0.12, -0.2]}
                          />
                          <group
                            position={[0.01, 0.02, 0.01]}
                            rotation={[-1.56, 0.07, -0.2]}
                          />
                          <group
                            position={[-0.01, 0.02, 0.01]}
                            rotation={[-1.56, 0.08, -0.2]}
                          />
                          <group
                            position={[-0.01, 0.02, 0]}
                            rotation={[-1.55, 0.09, -0.2]}
                          />
                          <group
                            position={[-0.02, 0.01, -0.01]}
                            rotation={[-1.54, 0.17, -0.2]}
                          />
                          <group
                            position={[-0.01, 0.02, -0.01]}
                            rotation={[-1.53, 0.2, -0.21]}
                          />
                          <group
                            position={[0, 0.02, -0.01]}
                            rotation={[-1.53, 0.21, -0.21]}
                          />
                          <group
                            position={[0.01, 0.02, 0]}
                            rotation={[-1.55, 0.1, -0.2]}
                          />
                          <group rotation={[-0.01, 0, 0.02]} />
                          <group rotation={[2.84, 0.73, -2.19]} />
                          <group rotation={[1.33, 1.26, -0.97]} />
                          <group rotation={[0.95, -1.19, 0.74]} />
                          <group rotation={[3, -0.16, 2.42]} />
                          <group rotation={[-2.98, 0.45, 2.02]} />
                          <group rotation={[-1.61, 1.22, 1.18]} />
                          <group rotation={[-0.31, -0.26, -0.06]} />
                          <group rotation={[-3.05, -0.17, -2.62]} />
                        </group>
                        <group
                          position={[-0.07, 0.01, 0.05]}
                          rotation={[-1.27, 0.12, 2.83]}
                        >
                          <group
                            position={[0, 0.05, -0.02]}
                            rotation={[0.18, 0.43, 0.28]}
                          />
                          <group
                            position={[0.01, 0, -0.02]}
                            rotation={[0.09, 0.68, 0.33]}
                          />
                          <group
                            position={[0, -0.02, -0.01]}
                            rotation={[0.07, 0.73, 0.35]}
                          />
                        </group>
                        <group
                          position={[0.07, 0, 0.05]}
                          rotation={[-1.24, -0.12, -2.86]}
                        >
                          <group
                            position={[0, 0.05, -0.02]}
                            rotation={[0.23, -0.45, -0.25]}
                          />
                          <group
                            position={[0, 0, -0.02]}
                            rotation={[0.17, -0.64, -0.28]}
                          />
                          <group
                            position={[0, -0.02, -0.01]}
                            rotation={[0.12, -0.77, -0.31]}
                          />
                        </group>
                        <group
                          position={[0, 0.03, 0.01]}
                          rotation={[2.51, -0.08, 3.13]}
                        >
                          <group
                            position={[0, 0.03, -0.02]}
                            rotation={[-0.43, -0.08, -0.02]}
                          >
                            <group
                              position={[0, 0.02, 0]}
                              rotation={[-1.77, 0, 0]}
                            />
                          </group>
                          <group
                            position={[0, 0.09, 0]}
                            rotation={[-2.2, 0.05, -0.08]}
                          >
                            <group
                              position={[0, 0.02, 0.01]}
                              rotation={[0, -0.01, 0]}
                            />
                          </group>
                          <group
                            position={[0.03, 0.07, 0]}
                            rotation={[-2.23, -0.34, -0.08]}
                          />
                          <group
                            position={[-0.03, 0.07, 0]}
                            rotation={[-2.18, 0.38, -0.08]}
                          />
                          <group
                            position={[0, 0.06, 0.03]}
                            rotation={[-2.2, 0.08, -0.08]}
                          />
                          <group
                            position={[0.05, 0.04, 0.01]}
                            rotation={[-2.17, 0.46, -0.09]}
                          />
                          <group
                            position={[-0.05, 0.04, 0]}
                            rotation={[-2.24, -0.44, -0.08]}
                          />
                          <group
                            position={[0, 0.03, -0.02]}
                            rotation={[-0.43, -0.08, -0.02]}
                          >
                            <group rotation={[-1.77, 0, 0]} />
                          </group>
                          <group
                            position={[0, 0.03, -0.02]}
                            rotation={[-0.43, -0.08, -0.02]}
                          >
                            <group
                              position={[0, -0.03, 0.01]}
                              rotation={[-1.77, 0, 0]}
                            />
                          </group>
                        </group>
                        <group
                          position={[-0.06, 0.07, 0.08]}
                          rotation={[-1.57, 0.05, 3.14]}
                        />
                        <group
                          position={[-0.06, 0.08, 0.09]}
                          rotation={[-1.57, -0.23, 3.14]}
                        />
                        <group
                          position={[-0.04, 0.1, 0.1]}
                          rotation={[-1.57, -0.18, 3.14]}
                        />
                        <group
                          position={[-0.02, 0.1, 0.09]}
                          rotation={[-1.57, -0.22, 3.14]}
                        />
                        <group
                          position={[0.06, 0.07, 0.08]}
                          rotation={[-1.57, 0.01, 3.14]}
                        />
                        <group
                          position={[0.06, 0.08, 0.09]}
                          rotation={[-1.57, 0.4, 3.14]}
                        />
                        <group
                          position={[0.04, 0.09, 0.1]}
                          rotation={[-1.57, 0.2, 3.14]}
                        />
                        <group
                          position={[0.02, 0.11, 0.09]}
                          rotation={[-1.57, 0.23, 3.14]}
                        />
                        <group
                          position={[-0.07, 0.03, 0.01]}
                          rotation={[-1.57, -0.2, 3.14]}
                        />
                        <group
                          position={[0.07, 0.02, 0.01]}
                          rotation={[-1.57, 0.23, 3.14]}
                        />
                        <group
                          position={[0, 0.11, 0.08]}
                          rotation={[-1.57, 0.04, 3.14]}
                        />
                        <group
                          position={[-0.02, 0.1, 0.06]}
                          rotation={[-1.57, -0.02, 3.14]}
                        />
                        <group
                          position={[0.02, 0.1, 0.06]}
                          rotation={[-1.57, 0.08, 3.14]}
                        />
                        <group
                          position={[0, 0.03, 0.01]}
                          rotation={[2.51, -0.08, 3.13]}
                        >
                          <group
                            position={[0, 0.07, -0.04]}
                            rotation={[-2.2, 0.09, -0.08]}
                          />
                        </group>
                        <group
                          position={[0, 0.03, 0.01]}
                          rotation={[2.51, -0.08, 3.13]}
                        >
                          <group
                            position={[0.02, 0.07, -0.04]}
                            rotation={[-2.2, 0.1, -0.08]}
                          />
                          <group
                            position={[-0.01, 0.07, -0.04]}
                            rotation={[-2.21, -0.02, -0.08]}
                          />
                        </group>
                        <group
                          position={[0, 0.03, 0.01]}
                          rotation={[2.51, -0.08, 3.13]}
                        >
                          <group
                            position={[0.06, 0.03, -0.03]}
                            rotation={[-2.21, -0.08, -0.08]}
                          />
                          <group
                            position={[-0.06, 0.03, -0.04]}
                            rotation={[-2.2, 0.15, -0.08]}
                          />
                          <group
                            position={[0.03, 0.06, -0.03]}
                            rotation={[-2.2, 0.1, -0.08]}
                          />
                          <group
                            position={[-0.02, 0.06, -0.04]}
                            rotation={[-2.21, -0.02, -0.08]}
                          />
                        </group>
                        <group
                          position={[0, 0.03, 0.01]}
                          rotation={[2.51, -0.08, 3.13]}
                        >
                          <group
                            position={[0.02, 0.07, -0.04]}
                            rotation={[-2.2, 0.1, -0.08]}
                          />
                          <group
                            position={[-0.01, 0.06, -0.05]}
                            rotation={[-2.21, -0.02, -0.08]}
                          />
                          <group
                            position={[0, 0.07, -0.05]}
                            rotation={[-2.21, 0.02, -0.08]}
                          />
                        </group>
                        <group
                          position={[0, 0.03, 0.01]}
                          rotation={[2.51, -0.08, 3.13]}
                        >
                          <group
                            position={[0.01, 0.06, -0.06]}
                            rotation={[2.5, 0.09, -3.1]}
                          >
                            <group
                              position={[0, 0.01, 0.02]}
                              rotation={[-1.57, 0, -3.13]}
                            >
                              <group
                                position={[0, 0.01, -0.01]}
                                rotation={[0, -0.02, 0]}
                              />
                              <group
                                position={[0, -0.01, -0.01]}
                                rotation={[0, 0.01, 0]}
                              />
                            </group>
                            <group rotation={[-1.57, 0.01, -3.13]} />
                            <group
                              position={[-0.02, -0.01, 0.01]}
                              rotation={[-1.57, -0.35, -3.13]}
                            />
                            <group
                              position={[0.02, -0.01, 0.01]}
                              rotation={[-1.58, 0.4, -3.13]}
                            />
                          </group>
                          <group
                            position={[0.05, 0.03, -0.07]}
                            rotation={[-2.25, -0.52, -0.09]}
                          />
                          <group
                            position={[-0.03, 0.02, -0.07]}
                            rotation={[-2.16, 0.58, -0.09]}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group position={[0, 0.27, 0]} rotation={[-1.42, 0, 0]}>
                  <group rotation={[1.79, 0, 0]}>
                    <group position={[0, 0.07, 0]} rotation={[-1.79, 0, 0]} />
                    <group position={[0, 0.03, 0]} />
                  </group>
                </group>
                <group position={[0.05, 0.21, 0]} rotation={[-1.42, 0, -1.35]}>
                  <group position={[0, 0.13, 0]} rotation={[1.63, 1.38, -2.15]}>
                    <group position={[0, 0.3, 0]} rotation={[0.03, 0, -0.01]}>
                      <group
                        position={[0, 0.24, 0]}
                        rotation={[-0.13, -0.01, 0.04]}
                      />
                      <group position={[0, 0.12, 0]} />
                    </group>
                    <group position={[0, 0.15, 0]} />
                  </group>
                  <group position={[0, 0.13, 0]} rotation={[0, 0, 1.35]}>
                    <group rotation={[1.58, 0.03, -2.09]}>
                      <group position={[0, 0.3, 0]} rotation={[0.03, 0, -0.01]}>
                        <group
                          position={[0, 0.24, 0]}
                          rotation={[-0.13, -0.01, 0.04]}
                        />
                      </group>
                    </group>
                    <group rotation={[1.57, 0.02, -2.1]}>
                      <group rotation={[-0.01, 0, 0]} />
                    </group>
                  </group>
                  <group
                    position={[0, 0.13, 0]}
                    rotation={[1.63, 1.38, -2.15]}
                  />
                  <group position={[0, 0.13, 0]} rotation={[1.63, 1.38, -2.15]}>
                    <group position={[0, 0.15, 0]}>
                      <group
                        position={[0, 0.15, 0]}
                        rotation={[0.03, 0, -0.01]}
                      >
                        <group position={[0, 0.12, 0]}>
                          <group
                            position={[0, 0.12, 0]}
                            rotation={[-0.13, -0.01, 0.04]}
                          >
                            <group
                              position={[0, 0.03, 0.02]}
                              rotation={[-2.6, 1.4, 3.03]}
                            >
                              <group
                                position={[0, 0.07, 0]}
                                rotation={[-1.97, -1.23, -2.05]}
                              >
                                <group
                                  position={[0, 0.05, 0]}
                                  rotation={[0.02, 0, -0.04]}
                                />
                              </group>
                              <group
                                position={[-0.02, -0.01, 0]}
                                rotation={[-1.52, 1.06, 1.49]}
                              >
                                <group
                                  position={[0, 0.07, 0]}
                                  rotation={[0.36, 0, 0.04]}
                                />
                              </group>
                              <group
                                position={[0, 0.07, 0]}
                                rotation={[-1.97, -1.23, -2.05]}
                              >
                                <group
                                  position={[0, 0.05, 0]}
                                  rotation={[0.02, 0, -0.04]}
                                />
                              </group>
                              <group
                                position={[-0.02, -0.01, 0]}
                                rotation={[-1.52, 1.06, 1.49]}
                              >
                                <group
                                  position={[0, 0.07, 0]}
                                  rotation={[0.36, 0, 0.04]}
                                />
                              </group>
                              <group
                                position={[0, 0.07, 0]}
                                rotation={[-1.97, -1.23, -2.05]}
                              >
                                <group
                                  position={[0, 0.05, 0]}
                                  rotation={[0.02, 0, -0.04]}
                                >
                                  <group
                                    position={[0, 0.03, 0]}
                                    rotation={[0.02, 0, 0.07]}
                                  />
                                </group>
                              </group>
                              <group
                                position={[-0.02, -0.01, 0]}
                                rotation={[-1.52, 1.06, 1.49]}
                              >
                                <group
                                  position={[0, 0.07, 0]}
                                  rotation={[0.36, 0, 0.04]}
                                >
                                  <group
                                    position={[0, 0.03, 0]}
                                    rotation={[0.03, 0, -0.07]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              position={[0, 0.03, 0.01]}
                              rotation={[-2.14, 1.5, 2.33]}
                            >
                              <group
                                position={[0, 0.07, 0]}
                                rotation={[0.08, -0.04, -0.06]}
                              >
                                <group
                                  position={[0, 0.05, 0]}
                                  rotation={[0.02, 0, 0]}
                                />
                              </group>
                              <group
                                position={[0, 0.07, 0]}
                                rotation={[0.08, -0.04, -0.06]}
                              >
                                <group
                                  position={[0, 0.05, 0]}
                                  rotation={[0.02, 0, 0]}
                                />
                              </group>
                              <group
                                position={[0, 0.07, 0]}
                                rotation={[0.08, -0.04, -0.06]}
                              >
                                <group
                                  position={[0, 0.05, 0]}
                                  rotation={[0.02, 0, 0]}
                                >
                                  <group
                                    position={[0, 0.03, 0]}
                                    rotation={[-0.04, 0, 0]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              position={[0, 0.03, 0]}
                              rotation={[0, 1.52, 0]}
                            >
                              <group
                                position={[0, 0.06, 0]}
                                rotation={[-0.1, 0.84, 0.17]}
                              >
                                <group
                                  position={[0, 0.04, 0]}
                                  rotation={[0.05, 0, 0.03]}
                                />
                              </group>
                              <group
                                position={[0, 0.06, 0]}
                                rotation={[-0.1, 0.84, 0.17]}
                              >
                                <group
                                  position={[0, 0.04, 0]}
                                  rotation={[0.05, 0, 0.03]}
                                />
                              </group>
                              <group
                                position={[0, 0.06, 0]}
                                rotation={[-0.1, 0.84, 0.17]}
                              >
                                <group
                                  position={[0, 0.04, 0]}
                                  rotation={[0.05, 0, 0.03]}
                                >
                                  <group
                                    position={[0, 0.03, 0]}
                                    rotation={[-0.04, 0, -0.07]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              position={[0, 0.03, -0.01]}
                              rotation={[0.23, 1.39, -0.43]}
                            >
                              <group
                                position={[0, 0.06, 0]}
                                rotation={[-2.65, 0.96, 2.56]}
                              >
                                <group
                                  position={[0, 0.03, 0]}
                                  rotation={[0, 0, 0.04]}
                                />
                              </group>
                              <group
                                position={[0, 0.06, 0]}
                                rotation={[-2.65, 0.96, 2.56]}
                              >
                                <group
                                  position={[0, 0.03, 0]}
                                  rotation={[0, 0, 0.04]}
                                />
                              </group>
                              <group
                                position={[0, 0.06, 0]}
                                rotation={[-2.65, 0.96, 2.56]}
                              >
                                <group
                                  position={[0, 0.03, 0]}
                                  rotation={[0, 0, 0.04]}
                                >
                                  <group
                                    position={[0, 0.02, 0]}
                                    rotation={[0.07, 0, -0.08]}
                                  />
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group position={[-0.05, 0.21, 0]} rotation={[-1.42, 0, 1.35]}>
                  <group position={[0, 0.13, 0]} rotation={[1.63, -1.38, 2.15]}>
                    <group position={[0, 0.3, 0]} rotation={[0.03, 0, 0.01]}>
                      <group
                        position={[0, 0.24, 0]}
                        rotation={[-0.13, 0.01, -0.04]}
                      />
                      <group position={[0, 0.12, 0]} />
                    </group>
                    <group position={[0, 0.15, 0]} />
                  </group>
                  <group position={[0, 0.13, 0]} rotation={[0, 0, -1.35]}>
                    <group rotation={[1.58, -0.03, 2.09]}>
                      <group position={[0, 0.3, 0]} rotation={[0.03, 0, 0.01]}>
                        <group
                          position={[0, 0.24, 0]}
                          rotation={[-0.13, 0.01, -0.04]}
                        />
                      </group>
                    </group>
                    <group rotation={[1.57, -0.02, 2.1]}>
                      <group rotation={[-0.01, 0, 0]} />
                    </group>
                  </group>
                  <group
                    position={[0, 0.13, 0]}
                    rotation={[1.63, -1.38, 2.15]}
                  />
                  <group position={[0, 0.13, 0]} rotation={[1.63, -1.38, 2.15]}>
                    <group position={[0, 0.15, 0]}>
                      <group position={[0, 0.15, 0]} rotation={[0.03, 0, 0.01]}>
                        <group position={[0, 0.12, 0]}>
                          <group
                            position={[0, 0.12, 0]}
                            rotation={[-0.13, 0.01, -0.04]}
                          >
                            <group
                              position={[0, 0.03, 0.02]}
                              rotation={[-2.6, -1.4, -3.03]}
                            >
                              <group
                                position={[0, 0.07, 0]}
                                rotation={[-1.98, 1.23, 2.06]}
                              >
                                <group
                                  position={[0, 0.05, 0]}
                                  rotation={[0.03, 0, 0.04]}
                                />
                              </group>
                              <group
                                position={[0.02, -0.01, 0]}
                                rotation={[-1.52, -1.06, -1.49]}
                              >
                                <group
                                  position={[0, 0.07, 0]}
                                  rotation={[0.36, 0, -0.04]}
                                />
                              </group>
                              <group
                                position={[0, 0.07, 0]}
                                rotation={[-1.98, 1.23, 2.06]}
                              >
                                <group
                                  position={[0, 0.05, 0]}
                                  rotation={[0.03, 0, 0.04]}
                                />
                              </group>
                              <group
                                position={[0.02, -0.01, 0]}
                                rotation={[-1.52, -1.06, -1.49]}
                              >
                                <group
                                  position={[0, 0.07, 0]}
                                  rotation={[0.36, 0, -0.04]}
                                />
                              </group>
                              <group
                                position={[0, 0.07, 0]}
                                rotation={[-1.98, 1.23, 2.06]}
                              >
                                <group
                                  position={[0, 0.05, 0]}
                                  rotation={[0.03, 0, 0.04]}
                                >
                                  <group
                                    position={[0, 0.03, 0]}
                                    rotation={[0.01, 0, -0.09]}
                                  />
                                </group>
                              </group>
                              <group
                                position={[0.02, -0.01, 0]}
                                rotation={[-1.52, -1.06, -1.49]}
                              >
                                <group
                                  position={[0, 0.07, 0]}
                                  rotation={[0.36, 0, -0.04]}
                                >
                                  <group
                                    position={[0, 0.03, 0]}
                                    rotation={[0.03, 0, 0.07]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              position={[0, 0.03, 0.01]}
                              rotation={[-2.14, -1.5, -2.33]}
                            >
                              <group
                                position={[0, 0.07, 0]}
                                rotation={[0.08, 0.04, 0.06]}
                              >
                                <group
                                  position={[0, 0.05, 0]}
                                  rotation={[0.02, 0, 0]}
                                />
                              </group>
                              <group
                                position={[0, 0.07, 0]}
                                rotation={[0.08, 0.04, 0.06]}
                              >
                                <group
                                  position={[0, 0.05, 0]}
                                  rotation={[0.02, 0, 0]}
                                />
                              </group>
                              <group
                                position={[0, 0.07, 0]}
                                rotation={[0.08, 0.04, 0.06]}
                              >
                                <group
                                  position={[0, 0.05, 0]}
                                  rotation={[0.02, 0, 0]}
                                >
                                  <group
                                    position={[0, 0.03, 0]}
                                    rotation={[-0.04, 0, 0]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              position={[0, 0.03, 0]}
                              rotation={[0, -1.52, 0]}
                            >
                              <group
                                position={[0, 0.06, 0]}
                                rotation={[-0.1, -0.84, -0.17]}
                              >
                                <group
                                  position={[0, 0.04, 0]}
                                  rotation={[0.05, 0, -0.03]}
                                />
                              </group>
                              <group
                                position={[0, 0.06, 0]}
                                rotation={[-0.1, -0.84, -0.17]}
                              >
                                <group
                                  position={[0, 0.04, 0]}
                                  rotation={[0.05, 0, -0.03]}
                                />
                              </group>
                              <group
                                position={[0, 0.06, 0]}
                                rotation={[-0.1, -0.84, -0.17]}
                              >
                                <group
                                  position={[0, 0.04, 0]}
                                  rotation={[0.05, 0, -0.03]}
                                >
                                  <group
                                    position={[0, 0.03, 0]}
                                    rotation={[-0.04, 0, 0.07]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              position={[0, 0.03, -0.01]}
                              rotation={[0.23, -1.39, 0.43]}
                            >
                              <group
                                position={[0, 0.06, 0]}
                                rotation={[-2.65, -0.96, -2.56]}
                              >
                                <group
                                  position={[0, 0.03, 0]}
                                  rotation={[0, 0, -0.04]}
                                />
                              </group>
                              <group
                                position={[0, 0.06, 0]}
                                rotation={[-2.65, -0.96, -2.56]}
                              >
                                <group
                                  position={[0, 0.03, 0]}
                                  rotation={[0, 0, -0.04]}
                                />
                              </group>
                              <group
                                position={[0, 0.06, 0]}
                                rotation={[-2.65, -0.96, -2.56]}
                              >
                                <group
                                  position={[0, 0.03, 0]}
                                  rotation={[0, 0, -0.04]}
                                >
                                  <group
                                    position={[0, 0.02, 0]}
                                    rotation={[0.07, 0, 0.08]}
                                  />
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group
                  position={[0.11, 0.03, 0.13]}
                  rotation={[-1.39, 0, -3.14]}
                >
                  <group position={[0, -0.02, 0]} rotation={[0.04, 0, 0]} />
                </group>
                <group
                  position={[-0.11, 0.03, 0.13]}
                  rotation={[-1.39, 0, Math.PI]}
                >
                  <group position={[0, -0.02, 0]} rotation={[0.04, 0, 0]} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
      <group position={[0.65, 1.2, -0.06]} rotation={[0.05, 0.12, -2.07]} />
      <group position={[0.5, 1.44, -0.59]} rotation={[1.92, -0.91, 0.17]} />
      <group position={[-0.65, 1.2, -0.06]} rotation={[0.05, -0.12, 2.07]} />
      <group position={[-0.5, 1.44, -0.59]} rotation={[1.92, 0.91, -0.17]} />
      <group position={[0.08, 0.04, -0.04]} rotation={[-Math.PI / 2, 0, 0.11]}>
        <group position={[0, -0.15, -0.04]}>
          <group position={[-0.02, 0.19, -0.01]}>
            <group position={[0.08, -0.01, 0]}>
              <group position={[-0.04, 0, 0]}>
                <group position={[-0.02, -0.18, 0.01]}>
                  <group
                    position={[0, 0.15, 0.04]}
                    rotation={[-2.87, 0.06, 0]}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
      <group position={[-0.24, 0.5, 0.87]} rotation={[-1.56, 0, -0.36]} />
      <group
        position={[-0.08, 0.04, -0.04]}
        rotation={[-Math.PI / 2, 0, -0.11]}
      >
        <group position={[0, -0.15, -0.04]}>
          <group position={[0.02, 0.19, -0.01]}>
            <group position={[-0.08, -0.01, 0]}>
              <group position={[0.04, 0, 0]}>
                <group position={[0.02, -0.18, 0.01]}>
                  <group
                    position={[0, 0.15, 0.04]}
                    rotation={[-2.87, -0.06, 0]}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
      <group position={[0.25, 0.5, 0.87]} rotation={[-1.56, 0, 0.37]} />
      <mesh
        geometry={nodes.Bra.geometry}
        material={materials.Bra_1_B115}
        scale={0.01}
      />
      <mesh
        geometry={nodes.CC_Base_Tongue.geometry}
        material={materials.Std_Tongue_1_B120}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Chin_Curtain_Sparse.geometry}
        material={materials.Beard_Transparency_1_B110}
        scale={0.01}
      />
    </group>
  );
}

// useGLTF.preload("/Thor-transformed.glb");
