/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Twerk({ ...props }) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF("/Twerk-transformed.glb");
    const { actions } = useAnimations(animations, group);

    useEffect(() => {
        console.log("This is Twerk MODEL ACTIONS", actions);
        setTimeout(() => {
            actions["mixamo.com"].play();
        }, 0);
    });

    return (
        <group ref={group} {...props} dispose={null}>
            <group>
                <group>
                    <primitive object={nodes.mixamorigHips2} />
                </group>
                <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <skinnedMesh
                        frustumCulled={false}
                        geometry={nodes.mesh_0.geometry}
                        material={nodes.mesh_0.material}
                        skeleton={nodes.mesh_0.skeleton}
                    />
                </group>
            </group>
        </group>
    );
}

// useGLTF.preload("/Twerk-transformed.glb");
