/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Two({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Two-transformed.glb");

  // Armor Color
  const color = "#3c1642";

  // Skin Color
  const color2 = "#086375";

  const { animations } = useGLTF("/Mirror.glb");

  // Pull animation from this glb
  // const { animations } = useGLTF("/RealGreyAnim.glb");
  const { actions } = useAnimations(animations, group);
  // console.log("This is Nodes GREY", nodes);
  // console.log("This is ACTIONS GREY", actions);

  useEffect(() => {
    // console.log("This is BAYC MODEL ACTIONS", actions);
    setTimeout(() => {
      // actions["CC_Base|FBXExportClip_0.001"].setEffectiveWeight(1);
      actions["Greylian2|FBXExportClip_0"].play();
    }, 0);
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="GreyMergeTestAETS001" scale={1}>
          <primitive object={nodes.CC_Base_BoneRoot} />
          {/* <skinnedMesh
                        frustumCulled={false}
                        name="ATES_M_Pouldrons_H"
                        geometry={nodes.ATES_M_Pouldrons_H.geometry}
                        material={materials.__meshes_Merge}
                        material-color={color}
                        skeleton={nodes.ATES_M_Pouldrons_H.skeleton}
                    />
                    <skinnedMesh
                        frustumCulled={false}
                        name="ATES_M_Suit_H"
                        geometry={nodes.ATES_M_Suit_H.geometry}
                        material={materials.__meshes_Merge}
                        material-color={color}
                        skeleton={nodes.ATES_M_Suit_H.skeleton}
                    /> */}

          {/* <group name="CC_Base_Body">
                        <skinnedMesh
                            frustumCulled={false}
                            name="CC_Base_Body_1"
                            geometry={nodes.CC_Base_Body_1.geometry}
                            material={materials.Std_Skin_Head}
                            skeleton={nodes.CC_Base_Body_1.skeleton}
                            material-color={color2}
                            morphTargetDictionary={
                                nodes.CC_Base_Body_1.morphTargetDictionary
                            }
                            morphTargetInfluences={
                                nodes.CC_Base_Body_1.morphTargetInfluences
                            }
                        />
                        <skinnedMesh
                            frustumCulled={false}
                            name="CC_Base_Body_2"
                            geometry={nodes.CC_Base_Body_2.geometry}
                            material={materials.Std_Skin_Body}
                            skeleton={nodes.CC_Base_Body_2.skeleton}
                            morphTargetDictionary={
                                nodes.CC_Base_Body_2.morphTargetDictionary
                            }
                            morphTargetInfluences={
                                nodes.CC_Base_Body_2.morphTargetInfluences
                            }
                        />
                        <skinnedMesh
                            frustumCulled={false}
                            name="CC_Base_Body_3"
                            geometry={nodes.CC_Base_Body_3.geometry}
                            material={materials.Std_Skin_Arm}
                            skeleton={nodes.CC_Base_Body_3.skeleton}
                            morphTargetDictionary={
                                nodes.CC_Base_Body_3.morphTargetDictionary
                            }
                            morphTargetInfluences={
                                nodes.CC_Base_Body_3.morphTargetInfluences
                            }
                        />
                        <skinnedMesh
                            frustumCulled={false}
                            name="CC_Base_Body_4"
                            geometry={nodes.CC_Base_Body_4.geometry}
                            material={materials.Std_Skin_Leg}
                            skeleton={nodes.CC_Base_Body_4.skeleton}
                            morphTargetDictionary={
                                nodes.CC_Base_Body_4.morphTargetDictionary
                            }
                            morphTargetInfluences={
                                nodes.CC_Base_Body_4.morphTargetInfluences
                            }
                        />
                        <skinnedMesh
                            frustumCulled={false}
                            name="CC_Base_Body_5"
                            geometry={nodes.CC_Base_Body_5.geometry}
                            material={materials.Std_Nails}
                            skeleton={nodes.CC_Base_Body_5.skeleton}
                            morphTargetDictionary={
                                nodes.CC_Base_Body_5.morphTargetDictionary
                            }
                            morphTargetInfluences={
                                nodes.CC_Base_Body_5.morphTargetInfluences
                            }
                        />
                        <skinnedMesh
                            frustumCulled={false}
                            name="CC_Base_Body_6"
                            geometry={nodes.CC_Base_Body_6.geometry}
                            material={materials.Std_Eyelash}
                            skeleton={nodes.CC_Base_Body_6.skeleton}
                            morphTargetDictionary={
                                nodes.CC_Base_Body_6.morphTargetDictionary
                            }
                            morphTargetInfluences={
                                nodes.CC_Base_Body_6.morphTargetInfluences
                            }
                        />
                    </group>
                    <group name="CC_Game_Eye">
                        <skinnedMesh
                            frustumCulled={false}
                            name="CC_Game_Eye_1"
                            geometry={nodes.CC_Game_Eye_1.geometry}
                            material={materials.Ga_Eye_R}
                            skeleton={nodes.CC_Game_Eye_1.skeleton}
                            morphTargetDictionary={
                                nodes.CC_Game_Eye_1.morphTargetDictionary
                            }
                            morphTargetInfluences={
                                nodes.CC_Game_Eye_1.morphTargetInfluences
                            }
                        />
                        <skinnedMesh
                            frustumCulled={false}
                            name="CC_Game_Eye_2"
                            geometry={nodes.CC_Game_Eye_2.geometry}
                            material={materials.Ga_Eye_L}
                            skeleton={nodes.CC_Game_Eye_2.skeleton}
                            morphTargetDictionary={
                                nodes.CC_Game_Eye_2.morphTargetDictionary
                            }
                            morphTargetInfluences={
                                nodes.CC_Game_Eye_2.morphTargetInfluences
                            }
                        />
                    </group>
                    <skinnedMesh
                        frustumCulled={false}
                        name="CC_Base_Tongue"
                        geometry={nodes.CC_Base_Tongue.geometry}
                        material={materials.Std_Tongue}
                        skeleton={nodes.CC_Base_Tongue.skeleton}
                        morphTargetDictionary={
                            nodes.CC_Base_Tongue.morphTargetDictionary
                        }
                        morphTargetInfluences={
                            nodes.CC_Base_Tongue.morphTargetInfluences
                        }
                    />
                    <group name="CC_Base_Teeth">
                        <skinnedMesh
                            frustumCulled={false}
                            name="CC_Base_Teeth_1"
                            geometry={nodes.CC_Base_Teeth_1.geometry}
                            material={materials.Std_Upper_Teeth}
                            skeleton={nodes.CC_Base_Teeth_1.skeleton}
                            morphTargetDictionary={
                                nodes.CC_Base_Teeth_1.morphTargetDictionary
                            }
                            morphTargetInfluences={
                                nodes.CC_Base_Teeth_1.morphTargetInfluences
                            }
                        />
                        <skinnedMesh
                            frustumCulled={false}
                            name="CC_Base_Teeth_2"
                            geometry={nodes.CC_Base_Teeth_2.geometry}
                            material={materials.Std_Lower_Teeth}
                            skeleton={nodes.CC_Base_Teeth_2.skeleton}
                            morphTargetDictionary={
                                nodes.CC_Base_Teeth_2.morphTargetDictionary
                            }
                            morphTargetInfluences={
                                nodes.CC_Base_Teeth_2.morphTargetInfluences
                            }
                        />
                    </group>

                    <group name="CC_Base_TearLine">
                        <skinnedMesh
                            frustumCulled={false}
                            name="CC_Base_TearLine_1"
                            geometry={nodes.CC_Base_TearLine_1.geometry}
                            material={materials.Std_Tearline_R}
                            skeleton={nodes.CC_Base_TearLine_1.skeleton}
                            morphTargetDictionary={
                                nodes.CC_Base_TearLine_1.morphTargetDictionary
                            }
                            morphTargetInfluences={
                                nodes.CC_Base_TearLine_1.morphTargetInfluences
                            }
                        />
                        <skinnedMesh
                            frustumCulled={false}
                            name="CC_Base_TearLine_2"
                            geometry={nodes.CC_Base_TearLine_2.geometry}
                            material={materials.Std_Tearline_L}
                            skeleton={nodes.CC_Base_TearLine_2.skeleton}
                            morphTargetDictionary={
                                nodes.CC_Base_TearLine_2.morphTargetDictionary
                            }
                            morphTargetInfluences={
                                nodes.CC_Base_TearLine_2.morphTargetInfluences
                            }
                        />
                    </group> */}
        </group>

        <group name="GreyMergeTestAETS" scale={1}>
          <group name="Shadow_Catcher" rotation={[-Math.PI / 2, 0, 0]}>
            <group name="CC_Base_Pivot" position={[0, 0, -1.53]}>
              <group name="Plane_001" position={[0, 0, 1.59]} />
            </group>
          </group>
        </group>

        <group name="GreyMergeTestNano001" scale={1} position={[0, -1, 0]}>
          <primitive object={nodes.CC_Base_BoneRoot_1} />
          <skinnedMesh
            frustumCulled={false}
            name="Nano_M_Suit_H"
            geometry={nodes.Nano_M_Suit_H.geometry}
            material={materials.Nano_M_Suit_H_Merge}
            material-color={color}
            skeleton={nodes.ATES_M_Suit_H.skeleton}
          />

          <group name="CC_Base_Body001">
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Body001_1"
              geometry={nodes.CC_Base_Body001_1.geometry}
              material={materials["Std_Skin_Head.001"]}
              material-color={color2}
              skeleton={nodes.CC_Base_Body_1.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Body001_1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Body001_1.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Body001_2"
              geometry={nodes.CC_Base_Body001_2.geometry}
              material={materials["Std_Skin_Body.001"]}
              skeleton={nodes.CC_Base_Body_2.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Body001_2.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Body001_2.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Body001_3"
              geometry={nodes.CC_Base_Body001_3.geometry}
              material={materials["Std_Skin_Arm.001"]}
              skeleton={nodes.CC_Base_Body_3.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Body001_3.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Body001_3.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Body001_4"
              geometry={nodes.CC_Base_Body001_4.geometry}
              material={materials["Std_Skin_Leg.001"]}
              skeleton={nodes.CC_Base_Body_4.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Body001_4.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Body001_4.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Body001_5"
              geometry={nodes.CC_Base_Body001_5.geometry}
              material={materials["Std_Nails.001"]}
              skeleton={nodes.CC_Base_Body_5.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Body001_5.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Body001_5.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Body001_6"
              geometry={nodes.CC_Base_Body001_6.geometry}
              material={materials["Std_Eyelash.001"]}
              skeleton={nodes.CC_Base_Body_6.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Body001_6.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Body001_6.morphTargetInfluences
              }
            />
          </group>

          <group name="CC_Base_TearLine001">
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_TearLine001_1"
              geometry={nodes.CC_Base_TearLine001_1.geometry}
              material={materials["Std_Tearline_R.001"]}
              skeleton={nodes.CC_Base_TearLine_1.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_TearLine001_1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_TearLine001_1.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_TearLine001_2"
              geometry={nodes.CC_Base_TearLine001_2.geometry}
              material={materials["Std_Tearline_L.001"]}
              skeleton={nodes.CC_Base_TearLine_2.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_TearLine001_2.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_TearLine001_2.morphTargetInfluences
              }
            />
          </group>
          <group name="CC_Base_Teeth001">
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Teeth001_1"
              geometry={nodes.CC_Base_Teeth001_1.geometry}
              material={materials["Std_Upper_Teeth.001"]}
              skeleton={nodes.CC_Base_Teeth_1.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Teeth001_1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Teeth001_1.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Teeth001_2"
              geometry={nodes.CC_Base_Teeth001_2.geometry}
              material={materials["Std_Lower_Teeth.001"]}
              skeleton={nodes.CC_Base_Teeth_2.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_Teeth001_2.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_Teeth001_2.morphTargetInfluences
              }
            />
          </group>
          <skinnedMesh
            frustumCulled={false}
            name="CC_Base_Tongue001"
            geometry={nodes.CC_Base_Tongue001.geometry}
            material={materials["Std_Tongue.001"]}
            skeleton={nodes.CC_Base_Tongue.skeleton}
            morphTargetDictionary={
              nodes.CC_Base_Tongue001.morphTargetDictionary
            }
            morphTargetInfluences={
              nodes.CC_Base_Tongue001.morphTargetInfluences
            }
          />
          <group name="CC_Game_Eye001">
            <skinnedMesh
              frustumCulled={false}
              name="CC_Game_Eye001_1"
              geometry={nodes.CC_Game_Eye001_1.geometry}
              material={materials["Ga_Eye_R.001"]}
              skeleton={nodes.CC_Game_Eye_1.skeleton}
              morphTargetDictionary={
                nodes.CC_Game_Eye001_1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Game_Eye001_1.morphTargetInfluences
              }
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Game_Eye001_2"
              geometry={nodes.CC_Game_Eye001_2.geometry}
              material={materials["Ga_Eye_L.001"]}
              skeleton={nodes.CC_Game_Eye_2.skeleton}
              morphTargetDictionary={
                nodes.CC_Game_Eye001_2.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Game_Eye001_2.morphTargetInfluences
              }
            />
          </group>
        </group>

        <group name="GreyMergeTestNano" scale={1}>
          <group name="Shadow_Catcher_1" rotation={[-Math.PI / 2, 0, 0]}>
            <group name="CC_Base_Pivot_1" position={[0, 0, -1.53]}>
              <group name="Plane_001_1" position={[0, 0, 1.59]} />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

// useGLTF.preload("/Two-transformed.glb");
