/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function UFO({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/UFO.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -0.1, 0]}>
        <mesh
          geometry={nodes.ufo_low_poly_Cylinder.geometry}
          material={materials.ufo_base_color}
        />
      </group>
    </group>
  );
}

// useGLTF.preload("/UFO.glb");
