/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Xeno({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Xeno-transformed.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.body.geometry}
        material={materials["07 - Default"]}
        position={[0, -0.06, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.head.geometry}
        material={materials["default"]}
        position={[0, -0.06, 0]}
        scale={0.01}
      />
    </group>
  );
}

// useGLTF.preload("/Xeno.glb");
